### ISSUE TITLE
Sluggish MovementHandler packets

### ISSUE THREAD

**Issue by ronancpl** [ronancpl/HeavenMS#126]
It turns out that some of the handlers that deals with the movement parsing (called by the client at every time frame) creates a list with new objects at every time.

Probably, some of the items of the list remains "constant/unaltered". If that's the case, there is no need to recreate the whole array thing again and again, maybe even it is possible to make use of a caching structure of sorts.

If someone is enlightened on this issue and is willing to help, please share a pull request with us.

**Comment by aiesha-1** [comment]
interesting find.
ive noticed the objectids for mobs and background objects are kinda funky, imo. does it even check to make sure that ols oid isnt being rewritten over when a new object spawn is made? lol

**Comment by ronancpl** [comment]
Actually getUsableOID() gives out an unused oid to be used for mobs and background objects, the check is being done... Overwrite problem occured when a player shared it's id (that is assumed to be their oid as well) with the field objects oids, this check wouldn't be done, but it is hoped to be fixed with the last commit.

**Comment by resinate** [comment]
what if u split the OIDS into sub sections ones for players, monsters, items and objects?

**Comment by RajanGrewal** [comment]
you can parse the movement structs as you go and process them, and then just grab the movement loop chunk and write it as a byte array to the outpacket thats gna b broadcasted.  if you want a collection of the movement structs tho id make it a fixed size array sinze loopcount is like the first byte in the packet.

check how xanadu does it : https://github.com/swordlegend/xanadu/blob/master/xanadu/player_movement_handler.cpp

**Comment by ronancpl** [comment]
The major issue with object creation on most MovementHandler packets has been cleared. Bravo, @Ubaware !
