### ISSUE TITLE
(Question) ExpRates

### ISSUE THREAD

**Issue by J0ker-0** [ronancpl/HeavenMS#138]
How do I change the exp rate to 666x? I can't seem to understand how you have implemented the exp rate limit.  I seem to be only able to change it 10x or lower.

**Comment by ronancpl** [comment]
All you need to know is that this server uses 2 rates, acting as multipliers. Server rates on ServerConstants and player rates. Player rates are updated each 20 levels, to disable it set USE_ADD_RATES_BY_LEVEL = false.

To apply a 777x exp rate, change the value at EXP_RATE to 777. Finally compile the project, and there you go.

**Comment by J0ker-0** [comment]
Yeah, I tried that. I've put 777x. Is there a reference else where?

**Comment by ronancpl** [comment]
![image](https://user-images.githubusercontent.com/9257761/33609313-c089a5f8-d9ae-11e7-95b4-ac0a20efbdc7.png)

Since there is level rates enabled, values can scale differently according to level. With said rates, at character level 1, this is the resulting rates.
