### ISSUE TITLE
Some system to HeavenMS

### ISSUE THREAD

**Issue by Soyrce** [ronancpl/HeavenMS#143]
hope you can add to AutoBan this message [exmaple]:
![image](https://user-images.githubusercontent.com/34108561/34222319-de52cb70-e5c3-11e7-9617-637e610293b6.png)

and this aweosome or touch me
![image](https://user-images.githubusercontent.com/34108561/34222376-0d080e6c-e5c4-11e7-98d7-a51b9895c83a.png)

**Comment by ronancpl** [comment]
Sorry, I won't be dealing with anything autoban-related. Regarding the 2nd feature, while it is good on an extent for a PS, I intend to refrain adding it since it seems to be rather a custom-ish info than a GMS feature.
