### ISSUE TITLE
Wash Fighter

### ISSUE THREAD

**Issue by lucasziron** [ronancpl/HeavenMS#144]
I have 4 base int + 629 with equip.
I am level 50 and I have 2583 of int.
When I use the AP, I withdraw 1 mp and put it in hp, I give it ok. the AP disappears and nothing happens.
What can this be ?

Ty

**Comment by lucasziron** [comment]
solved

**Comment by ronancpl** [comment]
The mechanics of AP resetting will take a stat point from some attribute and put it on another, whichever you pick. There are some limitations on which stats to take as well, depending on the character job.
