### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by Soyrce** [ronancpl/HeavenMS#145]
Hello ronan, just to know this quest broken or is it because i missed upload the WZ?
![image](https://user-images.githubusercontent.com/34108561/34340504-96b706b4-e98d-11e7-8338-f5f46b830eea.png)

**Comment by ronancpl** [comment]
There were some updates on the WZ regarding the Moren's questline, iirc. If the quest could not be started, check the prerequisites for this questline. If it could, maybe this is a WZ issue.
