### ISSUE TITLE
Kerning Pharmacy crash

### ISSUE THREAD

**Issue by lordtopcat** [ronancpl/HeavenMS#152]
Hi,

Great work, been using this for the last day or so and it's awesome.

One thing though, whenever I try and buy something from the Pharmacy in Kerning City, the game boots me out?

**Comment by ronancpl** [comment]
WZ's mismatch. This sources uses a custom (although GMS-like) WZ of it's own, that has diverged from the original v83 files, for both client and server sides.

**Comment by lordtopcat** [comment]
Oh thank you - quick question too...I just installed the client using the ManagerMsv83.exe ... do I then need to overwrite the wz files in there with the files from current_wz or rev158_wz? I remember now I got confused because in your readme it says the client_wz folder, of which I haven't got. Appreciate the clarification :-)

**Comment by ronancpl** [comment]
I have yet to update that section.
The folder to use depends on what version of the source on this repository is being used. If the feature-frozen one (the released one) is the one being used on the server-side, update the client-side with the rev158. If not, it is the hot-code one, so the current_wz one is the one to be used.

**Comment by lordtopcat** [comment]
Ohh right, gotcha! I zipped the hot-code version so will replace the client wz files with the files from current_wz.

Appreciate the speedy response! Thank you!
