### ISSUE TITLE
Pirate PQ

### ISSUE THREAD

**Issue by Soyrce** [ronancpl/HeavenMS#154]
Stage 1 Portal after kill all mobs cant go in portal.

Portal saying: cant go in yet. why? portal is broken?
![image](https://user-images.githubusercontent.com/34108561/34639118-4ba58944-f2e2-11e7-8a26-3f79936335a6.png)

**Comment by Soyrce** [comment]
https://media.discordapp.net/attachments/382929821455613952/399146341160452097/Screenshot_7.png?width=580&height=435

**Comment by ronancpl** [comment]
Check this portal script to discover whay it doesn't work properly. Use the "debugportal" command near a portal to check which script it uses. Since I've changed the Wz on this one as well, and here it does work fine, I'm closing this issue.
