### ISSUE TITLE
Error Running SQL Scripts to Setup DB

### ISSUE THREAD

**Issue by andrew-tam-000** [ronancpl/HeavenMS#156]
Hi there,

I am able to run the 'db_database.sql' script successfully.

However, when I try to run the 'db_drops.sql' script, I am getting the following DB error:

"ERROR 1364 (HY000) at line 19973: Field 'id' doesn't have a default value"

Is there something wrong with the sql script, or my setup perhaps?

**Comment by ronancpl** [comment]
The sql script works fine on this end.
