### ISSUE TITLE
Localhost download link seems to be infected with a virus

### ISSUE THREAD

**Issue by andrew-tam-000** [ronancpl/HeavenMS#157]
Hey there,

For either of the download links to the localhost:

https://hostr.co/r5QDmhlxpp8M
https://hostr.co/gJbLZITRVHmv

my windows defender is flagging it with the following:

Trojan:Win32/Tilken.B!cl

Is there an alternative link I can download the localhost.exe from?

**Comment by andrew-tam-000** [comment]
Perhaps uploading a version to that google drive may be a safe alternative?

**Comment by ronancpl** [comment]
Pretty much any localhost.exe found will be false-positively flagged by an antivirus, this is a problem running on every Maple PS scenario. It happens because the executable is a modified version of the original game client. Closing issue.
