### ISSUE TITLE
Problem with summon mob

### ISSUE THREAD

**Issue by Soyrce** [ronancpl/HeavenMS#158]
I've probably touched \ deleted a certain line related to Mob or whatever, and now every monster that !spawn BossID

**And I kill her. She does not disappear from the map.**
It disappears only if I change CH and return
  
*Just a boss*

**Comment by ronancpl** [comment]
Make sure the MaplePacketCreator.killMonster with the correct object id is being sent to the players on the map (causing them to disappear there).

**Comment by Soyrce** [comment]
there is no MaplePacketCreator.killMonster lines or whatever.

i replace your upload maplepacketcreator to mine old. and nothing changed
