### ISSUE TITLE
Some Quest List broken [and no IDQuest.js]

### ISSUE THREAD

**Issue by Soyrce** [ronancpl/HeavenMS#161]
the npc doesnt complete the quest
http://bbb.hidden-street.net/quest/job/whats-going-on-in-henesys
broken iron fragment still not dropping
^ warrior
http://bbb.hidden-street.net/quest/job/antique-search
antique not dropping from the chest (yeah its supposed to drop from a treasure chest)
^ bowman
http://bbb.hidden-street.net/quest/job/lost-book
searching for lost book but it doesnt drop in those maps
^ thief

**Comment by jaydenseah** [comment]
Have you tried solving yourself instead asking Ronan here?

**Comment by Soyrce** [comment]
I tried to fix myself, I added only the DROPS I hope I did right. drop_data

And I created an empty file of the Quest

**Comment by Soyrce** [comment]
Octopus Sample wont drop from octopus, i need it for a quest line :frowning:
quest is: Virus Sample Research

cant use the thorn remover on the thorns to remove them for the mushking empire quests

**Comment by ronancpl** [comment]
These issues you are bringing up are pretty much feature implementation of new quests into the source, be it inserting new script for npcs, add missing drop data to the SQL or others. MapleStory is gigantic in this aspect, it always will have missing information somewhere.
Issue troubleshooting should only be used to solve problems this source currently has, not to add new things that it still misses... For that it would be most welcomed to make use of Pull Requests: create and suggest a solution with these new features.

The current solution for the thorns doesn't expect one to "use" the Thorn Remover, rather one must have it in the inventory to pass the vines (one-time only). Alternatively, the player can pass if they have the quest "Exploring Mushroom Forest (3)" completed.

Issue solved.
