### ISSUE TITLE
One more issue with Mushroom Kingdom

### ISSUE THREAD

**Issue by iAlpex** [ronancpl/HeavenMS#163]
Thorn remover is not working. Is there a way to fix this or does anyone know how to fix it?

**Comment by ronancpl** [comment]
As it currently is, Thorn Remover is not intended to be used/consumed.

When a player moves near to the trigger portal (which uses the obstacle.js script), given the player has that item (id 2430015) in their inventory, the item should be deducted and the player would be warped to the next map. Acts as an one-time use.

**Comment by ronancpl** [comment]
Since a solution has been presented on this source, I'm closing this issue. If you still want to see answers to this question, please open a thread on RZ or other development forums regarding it.
