### ISSUE TITLE
Uncoded NPCs

### ISSUE THREAD

**Issue by seth1** [ronancpl/HeavenMS#166]
While playing the game I found 2 uncoded NPCs:

Chun Ji (9000007)
Who in modern GMS when clicked on says:
`Just a kid... Don't talk to me...`
and Water Filter (1092015) who says:
`I'm bored! Someone come play with me!`

There are probably more uncoded NPCs.

Also the newest update to portal sounds seems to have broken some portals for example entertraining (Mai's training camp on Maple Island). Removing the sound part fixes the portal.

Finally, what is the project philosophy on non-v83 things? For example later versions of GMS have added a "world map" to Showa town, or perhaps other pre-big bang maps such as Golden Temple, or prior regional things (such as coke town or taiwan).

**Comment by ronancpl** [comment]
On the issued portal scripts update there was a syntax case I had not checked, breaking some portals. It has been figured out now, there should be no syntax errors remaining for the portal scripts.

Now, regarding non-v83 things. While the source code updates is expected to be version-agnostic, this project revolves in work safely under the provided WZ and XML files, that happens to be a branch from the v83 GMS.

That said, I believe other GMS versions may still kick in to the game screen, given the opcodes and other configurations have been properly set on the server source. Personally, there is no plans to backport contents from later versions and make it work here.
