### ISSUE TITLE
Loot Issue

### ISSUE THREAD

**Issue by iAlpex** [ronancpl/HeavenMS#169]
Anytime I kill a mob and it drops anything within a certain distance of my character there is a long loot delay. How does one go about removing the delay?

**Comment by ronancpl** [comment]
MapleMapItem has an issue with how character_ownerid is being assigned. When on a party, it uses the party id as the owner of the item. To solve, simply assign to it the character id, disregard party id.

**Comment by ronancpl** [comment]
This is supposed to be solved by now, after the last commit. Closing issue.
