### ISSUE TITLE
Cannot delete a character without a PIC in character select stage

### ISSUE THREAD

**Issue by Reeeeeemi** [ronancpl/HeavenMS#170]
It seems not working even I manually set PIN/PIC in MySQL>heavenms>accounts

**Comment by ronancpl** [comment]
To delete a character, it is mandatory the ENABLE_PIC flag set as true. This way, the system will start inquiring PIC's when transactioning accounts inside the game. By confirming the PIC, the character will be deleted.

**Comment by Reeeeeemi** [comment]
Thanks. It works now. BTW, what's the difference between PIN and PIC. Should I also enable PIN?

**Comment by ronancpl** [comment]
PIN/PIC are merely extra security for one's account when logging in the game.

PIN: 4-digit passcode required to access one's account.
PIC: 6-digit passcode required to access one's character.

Save for deleting character, PIN/PIC are optional features.

**Comment by Reeeeeemi** [comment]
Thanks for your kind explanation.
