### ISSUE TITLE
Attack damage has no delay

### ISSUE THREAD

**Issue by Reeeeeemi** [ronancpl/HeavenMS#171]
I can feel that the attack is done instantly even before I hit the monster which seems a bit unnatural. I'm sure if it should be like this inherently as I played MS very long time ago. 
![ms](https://user-images.githubusercontent.com/14024960/36936881-d7a50264-1f45-11e8-97de-de89e2fc1157.gif)

**Comment by ronancpl** [comment]
It is supposed to be like this, I suppose. Since you are running a localhost, there is practically no lag on the client/server communication, hence you see this not-so-natural effect.

**Comment by Reeeeeemi** [comment]
Thanks. Then this might not be an issue. Closed.
