### ISSUE TITLE
LudiPQ, OrbisPQ Script Error Help Me T_T

### ISSUE THREAD

**Issue by you16471** [ronancpl/HeavenMS#173]
![pqerror](https://user-images.githubusercontent.com/37094930/37070988-a51bfc8e-21fd-11e8-94d4-637dab45090a.jpg)

I'm Using Windows 10 64-bit, installed JDK 7u79 and Netbeans 8.0.2...
how can i fix these errors?? TT

**Comment by ronancpl** [comment]
There were indeed some logic errors with those PQs, OrbisPQ hadn't instanced the statusStg0 property beforehand and LudiPQ hadn't instanced the combo property properly before using it. That's solved by now.
