### ISSUE TITLE
Quest Display Problem

### ISSUE THREAD

**Issue by macsun1990** [ronancpl/HeavenMS#175]
Many quest display have some "n", how to fix it?

![image](https://user-images.githubusercontent.com/35826887/37404126-e115d038-27cb-11e8-8d00-859368278d89.png)

**Comment by ronancpl** [comment]
Some localhosts out there shows these issues. There is one I edited, available through the readme, that solves this issue.

**Comment by macsun1990** [comment]
Sorry,I readed the "Readme" but still not find the way.I try to download different localhost.exe "https://hostr.co/gJbLZITRVHmv" and  "https://hostr.co/r5QDmhlxpp8M" but still have that problem.Can you help me to fix it?

**Comment by ronancpl** [comment]
I've downloaded the recommended localhost (https://hostr.co/r5QDmhlxpp8M) and tested it, worked properly.

![image](https://user-images.githubusercontent.com/9257761/37440376-2867d1d4-27db-11e8-8c52-f9b604b47bde.png)

**Comment by macsun1990** [comment]
That's ok now,i fix with https://hostr.co/r5QDmhlxpp8M. Thank you!
