### ISSUE TITLE
The NX pick up banner

### ISSUE THREAD

**Issue by macsun1990** [ronancpl/HeavenMS#176]
Hi,Ronan
 The NX pick up banner is too long.I want  to modify the banner. How to do it?
![image](https://user-images.githubusercontent.com/35826887/37464330-f537ebf6-2892-11e8-8cad-f55948e3e0c3.png)

**Comment by ronancpl** [comment]
Check the announceHint function on MapleClient, it specifies the desired length for the banner.

**Comment by macsun1990** [comment]
OK,That's right. Thank you.
![image](https://user-images.githubusercontent.com/35826887/37465522-509f6df4-2896-11e8-9f4a-d69c551abd89.png)
