### ISSUE TITLE
Disable the equips level up

### ISSUE THREAD

**Issue by macsun1990** [ronancpl/HeavenMS#178]
Hi.Ronan
   The now question is how to disable the equips level upgread.
![image](https://user-images.githubusercontent.com/35826887/37466384-8aae790c-2898-11e8-959c-e50e514ba16d.png)

**Comment by vcoc** [comment]
Dude, go to the discord and ask to him

**Comment by ronancpl** [comment]
For further questions, please use the Discord channel: https://discord.gg/Q7wKxHX.

On ServerConstants, set USE_EQUIPMNT_LVLUP to 1, it will disable normal equip upgrading.

**Comment by vcoc** [comment]
HeavenMS: https://discord.gg/Q7wKxHX

**Comment by macsun1990** [comment]
Ok.Thanks all
