### ISSUE TITLE
changing monster HP from int to LONG

### ISSUE THREAD

**Issue by resinate** [ronancpl/HeavenMS#179]
if u look at the code only code sent to client is % based HP, i did manage to convert hp to long values would be nice to see if official. you cant even tell the difference on client side when playing. just something really useful for custom events ppl can make.

a question however: is pirate SHIP and other mounts count as a monster with HP when read in the system?

**Comment by ronancpl** [comment]
Answering your question, yes the pirate ship has an HP of it's own, iirc. Normal mounts doesn't have HP of it's own, although one could extrapolate that using the mob tiredness as a "HP of sorts".

**Comment by ronancpl** [comment]
customShowBossHP() packet function now uses % based HP.
