### ISSUE TITLE
Auto registration 

### ISSUE THREAD

**Issue by JaFont** [ronancpl/HeavenMS#181]
Auto register doesn’t not work. It spits back an invalid birthday message.

**Comment by ronancpl** [comment]
This issue will show up when trying to run the DB on later versions of MySQL (e.g. when using MySQL workbench).

Since this project is supposed to use legacy version (MySQL Query Browser), and for that version no such issues arises, i'm closing this issue.

**Comment by JaFont** [comment]
I’m using MySQL query browser 1.1.20, is that too high?

**Comment by ronancpl** [comment]
MySQL version being used: '5.1.36-community-log' (use "SELECT @@version;" to find out)
Query Browser version matches.
WampServer version 2.0
