### ISSUE TITLE
Small List of bugs

### ISSUE THREAD

**Issue by iAlpex** [ronancpl/HeavenMS#182]
SKILLS:
Ninja Ambush - Shows damage but does not do damage.
Flame Gear - Does damage but when the mob catches flame it does no damage.

QUESTS:

Aran questline: The Puppeteer's Cave - When you enter the password at the cave it's not letting you enter saying in pink "Although you answered right, some mysterious forces is blocking the way in." Password is "Francis is a genius Puppeteer!"

Kerning Quest: The monster and the evil scheme - nothing happens after clicking the trash thingy in the hut 

Where do I go about to fix this issue?

**Comment by ronancpl** [comment]
Although Ninja Ambush was quite unbalanced until today, it did do damage-over-time damage, and so do flame gear. There's also the idea that the DOT damage does not go under 1. Is that what prompted your issue claim?

For the Aran questline, you need to meet certain conditions to enter the cave:
```
if(cm.isQuestStarted(20730) && cm.getQuestProgress(20730, 9300285) == 0)
	cm.warp(910510001, 1);
else if(cm.isQuestStarted(21731) && cm.getQuestProgress(21731, 9300346) == 0)
	cm.warp(910510001, 1);
```

The kerning questline has been added now, thanks for the feedback. Is that issue solved?

**Comment by iAlpex** [comment]
Okay so Flame Gear and Ninja Ambush wont allow the mob to go under 1 HP?

aran questline -  where is that code supposed to be? which npc? i dont have an npc script with that code in it.

Kerning Questline - Thank you for the add in. Much appreciated.

After aran questline is complete that will resolve all my issues at the moment.

**Comment by iAlpex** [comment]
After looking further into the questline of Aran it is found that The quest 21728 does not complete when you accept the quest and go to the cave. i may be wrong but manually completing it in the database will cause you not to be able to accept the next quest which is 20730. or 21731

**Comment by ronancpl** [comment]
That's supposed to be closed by now, since proper support has been applied to solve that issue. Quest.wz has been updated to implement the solution.
