### ISSUE TITLE
Perion NPCs

### ISSUE THREAD

**Issue by theveug** [ronancpl/HeavenMS#183]
The Taxi and Package Delivery NPCs are missing, only the truck and taxi sign are there.
The world tour guide is also down bottom away from her stand.

**Comment by ronancpl** [comment]
This may happen if you are using the clean v83 WZ files and the currently updated wz.xml server files. To solve that either use clean wz.xml files or the updated wz files.

**Comment by theveug** [comment]
You were right, using the clean wz files for client side worked.
