### ISSUE TITLE
Autoban issue

### ISSUE THREAD

**Issue by iAlpex** [ronancpl/HeavenMS#187]
Certain skills from Buccaneer and Brawler show up as DMG Hack and autoban players. Showing they hit a certain dmg and max damage is 0. How can I fix this?

The skills are Shockwave w/ Transformation, Energy Blast, and Energy Charge.
ScreenShot: https://gyazo.com/e3cbabbb831d025b1d5b6224d40f11a2

**Comment by ronancpl** [comment]
The autoban system is not going to be approached here. To find a solution for them, locate the handler files that communicates with the autoban system and check what is going on there that results on these false positive bans. They are generally the attack handlers.
