### ISSUE TITLE
ServerConstant doesn't control exp rates

### ISSUE THREAD

**Issue by krnkamja** [ronancpl/HeavenMS#191]
I changed exp rates in serverconstant but it is fixed by some other algorithm. When i kill a stump it is x8 while when I kill a red snail its like x10.
And also quest exp rate is fixed at x10 also.

**Comment by krnkamja** [comment]
And yes, i set use_add_rates_by_level to false. Still exp rate isn't controlled by serverconstant values

**Comment by lujeff** [comment]
Did you build the project before re-running the .bat file?

**Comment by krnkamja** [comment]
Yes I did. And still no changes. in fact I dont think anything I changed on serverconstants.java changed in the game after building the project and re-running the .bat file

**Comment by lujeff** [comment]
Did you open the source files as an existing project or did you make a new project and added the source files?

Your compiled builds may be in a seperate folder and you'd have to replace the server's files with the newly built ones.

**Comment by krnkamja** [comment]
oh thank you
When i reopened and clean and built the project it changed it
