### ISSUE TITLE
Batt Error!

### ISSUE THREAD

**Issue by freshmany** [ronancpl/HeavenMS#194]
everything working fine, but this happen every 15-20mins bat error popup
https://ibb.co/iu7Cqo

this leads to a deadlock problem, and im sure of it?

why does this happen to me and if u can help me how to fix this thanks

im using java 8 -

when i use java 7 the server bat, wont start and earror

so am using java 8

**Comment by freshmany** [comment]
When i install java 7 again and when i start the bat. this is what error i get and starter wont start
https://ibb.co/fHnU5o

**Comment by freshmany** [comment]
fixed!.... also when i put other files in wz.
then the server wont start.

then i re extract your server files agian it work normally, when i want higher version items etc i put in wz area then server wont start and give me error?

it use to work in commit 140 below -
so now its 199, how does it work? and help tips program?

**Comment by ronancpl** [comment]
Sorry, can vouch for backporting features from higher versions. Probably some node / set of nodes you're trying to add is using some unsupported info. You should work it out with trial and error, narrowing down what could be going wrong.
