### ISSUE TITLE
Scissors of Karma does not change the untradable item, to tradable item.

### ISSUE THREAD

**Issue by vince538** [ronancpl/HeavenMS#195]
You can buy sciccors of karma from the cashshop and you can also open it.
After opening and placing an untradable item ( for example skillbook) in it,, and press the button.
You will get the message "You have used the scissors of Karma, so 1 time of trading has been enabled".
But the item stays untradable after this message.

**Comment by ronancpl** [comment]
It winds up Scissors of Karma uses two flags for it's effect, depending on whether the item is an equip or an use.

```
KARMA_USE = 0x02;
KARMA_EQP = 0x10;
```

Changing entry code points for Karma to make them set/check up the proper flag value solves the issue. Also, there are quite a few code sections that need a proper logic review to make the Karma effect work smoothly.

**Comment by vince538** [comment]
How do i make the karma effect run smoothly?
I found KARMA in Itemconstants it's set for equips only at 0x10
Do i change the static variable to KARMA_EQP and create another static variable KARMA_USE = 0x02;

What else is involved? MapleTrade or the UseCashItemHandler? I'd really like to learn.

**Comment by ronancpl** [comment]
Yes, change that to and create the other static variable. After that, manage the Karma flag attributions to use the previous item's flag bit-wise added the Karma attribute. All files that uses the KARMA flag is involved.

```
    public static void setKarmaFlag(Item item) {
        int karmaFlag = getKarmaFlag(item);  //0x02 to use; 0x10 to eqp
        int flag = item.getFlag();
        
        flag |= karmaFlag;
        item.setFlag((byte) flag);
    }
```

**Comment by iAlpex** [comment]
quick question. The 0x02 is used for Spikes correct? so wouldnt that interfere with the Karma_USE?

**Comment by ronancpl** [comment]
Not at all. Both uses the same bitfield, but Spikes effect shows up on equipment only and Karma shows up on uses only (on that bitfield, 0x10 shows Karma on equips).

**Comment by iAlpex** [comment]
so the code should look like this?

` 
    public final static int LOCK = 0x01;
    public final static int SPIKES = 0x02;
    public final static int COLD = 0x04;
    public final static int UNTRADEABLE = 0x08;
    public final static int KARMA_USE = 0x02;
    public final static int KARMA_EQP = 0x10;
    public final static int PET_COME = 0x80;
    public final static int ACCOUNT_SHARING = 0x100;`

in item constants? and then place 
`public static void setKarmaFlag(Item item) {
        int karmaFlag = getKarmaFlag(item);  //0x02 to use; 0x10 to eqp
        int flag = item.getFlag();
        
        flag |= karmaFlag;
        item.setFlag((byte) flag);
    }` 
in itemconstants as well?

**Comment by ronancpl** [comment]
Yea, it could be done that way.

**Comment by ronancpl** [comment]
Full Karma support has been implemented now. Issue closed.
