### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by BangPower** [ronancpl/HeavenMS#196]
its not really an issue its just annoying,
after you do your pic your character still walks until you re log and then you can actually login to the game.

**Comment by ronancpl** [comment]
Couldn't reproduce this problem at firsthand. You mean somehow the login phase freezes when trying to use pic, only logging out and re-auth into the account to bypass it? Or that's actually a loading delay, if so does the character you're trying to login has made quite some progress in the game already?

**Comment by BangPower** [comment]
nope, is just for the first time with the account when you for the first time enter your pic the avatar walks and you need to re log in order to pass the character screen i mean its happening only once to each and every player for his first time doing pic.

**Comment by BangPower** [comment]
and one more question!
im runing a server with your source but there is any way to keep the server runing and still update it with your updates? with out hurting the SQL data or anything else? like somthing that would just upgrade it and not replace it, like when you use SVN.

**Comment by ronancpl** [comment]
The only option is to nitpick the changes you want to have on your server. Be aware, here the server xml's, wz's and sql's are under constant changes at every commit, so I strongly suggest you to thoroughly manage every new content update you want live. New content here is not supposed to be supported by old resource files versions.

**Comment by ronancpl** [comment]
About the login issue, I created a new account through autoregister, created an logged in after registering PIC, loaded smoothly.
