### ISSUE TITLE
Pet dried up upon purchase from cashshop.

### ISSUE THREAD

**Issue by BangPower** [ronancpl/HeavenMS#201]
Thank you for helping me with fixing the other issues.
hmm...whenever i purchase any pet from the cash shop it comes off dead like a puppet and i need to buy water of life in order to resuscitate.
can you help me why whenever someone buy pets they come dead? pet dried up.

**Comment by ronancpl** [comment]
Check the expiration time of the generated pet item on the DB. It's supposed to have a future time value there.

![image](https://user-images.githubusercontent.com/9257761/40622520-6c661cb0-6278-11e8-82a4-ee32701ca9e6.png)

**Comment by BangPower** [comment]
i cant find this tab on my SQL.
and i don't understand how does it related to the SQL?
when i purchase a dead pet isn't it something on the source that need to be fixed?

**Comment by BangPower** [comment]
Ok and found it.
but how do i command the cash shop to give them et with a 90 days expiration and not dead pets?

**Comment by ronancpl** [comment]
Apply the same mechanic buying pet from the cash shop does and apply it on the item generate command. Creating pet requires add a row representing it on the DB or else the mob shows up as dead. ````MaplePet.createPet(int itemid)``` creates said SQL row, then add an expiration and I think it's all set.
