### ISSUE TITLE
every merchant dc

### ISSUE THREAD

**Issue by BangPower** [ronancpl/HeavenMS#202]
every merchant to buy pots dc the the players when they click.
at the beginning i thought it because the "npc id" nad shop id are the same so i changed the shop ids and the shopitemids and it worked but after certain time again you cant click the npc its dc you, someone told me something about benish scroll? no idea.
please help me to resolve this!

**Comment by ronancpl** [comment]
Your Wz's lacks node data for itemid 2030100. Either remove shop entries for 2030100 from the SQL's or add the missing feature on Item.wz and String.wz.
