### ISSUE TITLE
NullPointerException at server.maps.MapleMap.getGroundBelow

### ISSUE THREAD

**Issue by steven1152** [ronancpl/HeavenMS#207]
`java.lang.NullPointerException
	at server.maps.MapleMap.getGroundBelow(MapleMap.java:1747)
	at server.maps.MapleMap.addPlayer(MapleMap.java:2379)
	at client.MapleCharacter.changeMapInternal(MapleCharacter.java:1468)
	at client.MapleCharacter.changeMap(MapleCharacter.java:1318)
	at server.maps.MapleGenericPortal.enterPortal(MapleGenericPortal.java:148)
	at net.server.channel.handlers.ChangeMapHandler.handlePacket(ChangeMapHandler.java:153)
	at net.MapleServerHandler.messageReceived(MapleServerHandler.java:166)`

Steps to reproduce (100% success rate for me):
1. Go to "The town of Ariant" (260000200)
2. Go to the very right, enter the invisible portal below the NPC Sejan, do not move once inside the map "An Old, Empty House" (260000201)
3. Enter the portal to get out immediately
4. The exception occurs and the character is stuck until logging out and logging in again.

This issue has happens more than once in more than one map, I unfortunately did not take note of where else it happened, I believe it happened at least once somewhere deep inside the Sleepywood dungeon.

**Comment by ronancpl** [comment]
Couldn't reproduce this issue, seems to run smoothly here.

**Comment by steven1152** [comment]
The following file is a video showing the issue.
[heavenms-2018-06-06 20-03-46.zip](https://github.com/ronancpl/HeavenMS/files/2078519/heavenms-2018-06-06.20-03-46.zip)
I tried with clean and updated server and client files and it still happens.
I then realized the issue only happens if I have a pet.

**Comment by ronancpl** [comment]
```
   public Point getGroundBelow(Point pos) {
        Point spos = new Point(pos.x, pos.y - 14); // Using -14 fixes spawning pets causing a lot of issues.
        spos = calcPointBelow(spos);
        spos.y--;//shouldn't be null!
        return spos;
    }
```

This will solve Ariant's issue, lemme know if the null still happens elsewhere.
