### ISSUE TITLE
Issue with Wedding

### ISSUE THREAD

**Issue by iAlpex** [ronancpl/HeavenMS#209]
slight issue with wedding. everything goes well up to the time you have to answer yes or no to get married. in the wedding cathedral. here is the traceprint below
[9201002.txt](https://github.com/ronancpl/HeavenMS/files/2082976/9201002.txt)

**Comment by ronancpl** [comment]
On MapleCharacter, add:

```
    public boolean haveItemEquipped(int itemid) {
        return (inventory[MapleInventoryType.EQUIPPED.ordinal()].findById(itemid) != null);
    }
```

**Comment by iAlpex** [comment]
great! Going to test it now. Thanks!

**Comment by ronancpl** [comment]
On MaplepacketCreator, line 2110:
```mplew.writeInt(ring.getItemId());```

Issue solved.
