### ISSUE TITLE
HolidayPQ NPC Non-Responsive

### ISSUE THREAD

**Issue by yennagi** [ronancpl/HeavenMS#212]
Hey there,

When I reach to HappyVille and click on the the HolidayPQ npc, nothing pops up. I checked the launch.bat to see if there were any errors that would be displayed but there weren't any errors.

**Comment by ronancpl** [comment]
That NPC uses quest-based scripts for the interaction, the warp to the PQ area revolves around that. Also, it still doesn't have a message to show when click, so it would seem indeed unresponsive at first. The quest for that is limited between level 21~50, the quest baloon should pop up under this scenario.

**Comment by yennagi** [comment]
I had 3 characters at level 30 and we were in a party, when I clicked on the NPC it did not respond. Is it because there needs to be more than 3 people in a party in order to do the PQ?

**Comment by ronancpl** [comment]
Check if the Quest.wz is updated, since that quest should be expired hence unavailable otherwise. Once started the quest, you should be able to be sent to the actual PQ area.

**Comment by ronancpl** [comment]
New message data has been added for this NPC, to make it look responsive at first glance. Thanks for the feedback!
