### ISSUE TITLE
Java 8 for MapScriptManager

### ISSUE THREAD

**Issue by Arufonsu** [ronancpl/HeavenMS#216]
```
        FileReader fr = null;
        ScriptEngine portal = sef.getScriptEngine();
        try {
            fr = new FileReader(scriptFile);
// we add nashorn support for java 8 here to prevent problems //
//
            	if (ServerConstants.JAVA_8){
            		portal.eval("load('nashorn:mozilla_compat.js');" + System.lineSeparator());
            	}            
// (By Arufonsu) //
            CompiledScript compiled = ((Compilable) portal).compile(fr);
            compiled.eval();
```
we need to load java 8 when needed in the map scripts, also the em.getTransportationTime lines should be commented out from the boats and other transportation scripts (?) (i did so, and since the vars have the required timers declared first... so these lines doesn't seems to affect the scripts.... now i can run boats and everything without problems using java 8! please somebody correct me if im wrong);
also, can i join the repo? i really loved this source!

**Comment by ronancpl** [comment]
Added code to cover this aspect of java 8 support. It wasn't tested though.

Anyone is welcome to contrubute to the project, either giveing feedbacks or actively contributing with code. The latter will be covered via Pull Requests.

**Comment by Arufonsu** [comment]
i know you closed this, ive tested the java 8 support you added to abstract script manager, BuT! it not loading nashorn on other scriot types such as portal ones, thats why i added these line here in case they were necessary on the source.

**Comment by ronancpl** [comment]
Looking the source all script types supposedly received support for Java 8 already. That comprises of AbstractScriptManager (handles npc, event, quest, reactor), ItemScriptManager, MapScriptManager and PortalScriptManager.

In case just few things are missing, let me know. Having a proper solution for the Java 8 support with scripts, I will gladly accept a pull request for that.
