### ISSUE TITLE
 ENABLE_PIC (enabled) = Register PIC works - NOT AN ISSUE (CLOSE THIS)

### ISSUE THREAD

**Issue by Arufonsu** [ronancpl/HeavenMS#217]
EDIT:
To delete a character, ENABLE_PIC is required true. and you can register the PIC after you select START game with your **first** character! 
please change the tag of this, as is not an issue!  
sorry ... -facepalm-

**Comment by jaydenseah** [comment]
You can turn off Enable PIC in serverconstants. I've no idea why you hardcode PIC in.

**Comment by Arufonsu** [comment]
yeah. i know it can be turned off, but people might want to delete characters!
and the PIC enabled is useless if the PIC isn't even set up x.x

could probably do a work around for PICs on a website registration..
so, is it possible to call the create PIC popup after the TOS and gender select? (i believe that GMS had this that way a long time ago.)

**Comment by ronancpl** [comment]
The PIC popup signal is sent to the client at the moment they select a world to play. There's no way to match the intention of the player (to delete a character that is) without scraping the ENABLE_PIC feature, forcing everyone to auth the PIC to log into the game. That's why to delete a character ENABLE_PIC is required true.

**Comment by Arufonsu** [comment]
Yes!
when i enabled PIC, i tried to create an account from 0 and...
logged in..
TOS...
gender...
world select...
creates character...
tries to delete character...
PIC is requested, but NEVER got a popup to CREATE a PIC... this is why i left this default hardcoded PIC

does it has anything to do with this?...
`mplew.write(ServerConstants.ENABLE_PIC ? (c.getPic() == null ? 0 : 1) : 2); // 0 = Register PIC, 1 = Ask for PIC, 2 = Disabled`


i want the server to send the 0 = Register  PIC at some point of the first auto login so players can delete their characters !
