### ISSUE TITLE
Can't go past character select screen with java 7

### ISSUE THREAD

**Issue by Arufonsu** [ronancpl/HeavenMS#218]
no scripts error, no sql errors
used the jdk x64 installer provided here.
added the (JCE) Unlimited Strength files to the right folders.
but not i can't get in the game...
no errors in console, just a dc saying already logged in, tried to set logged in to 0 in database, no solution
the game was playable with java 8, but after  uninstalling it and try the jdk 7 and jces, i can't go past char screen.

same problem from: http://forum.ragezone.com/f566/moopledev-v83-rev-120-unable-1062463/

**Comment by ronancpl** [comment]
I'm sorry for the inconvenience, but personally I won't be working towards Java 8 compatibility. Still, if anyone manages to make Java 8 run smoothly on their side and wants to share their find, I will gladly be accepting a pull request for it.

**Comment by ronancpl** [comment]
Did you test locally already?

**Comment by Arufonsu** [comment]
yes, local and public
i was running a server public and playing with a friend
but when downgrade from java 8 -> java 7  i can go past character select

no scripts error, no sql errors
used the jdk x64 installer you provided
added the (JCE) Unlimited Strength files to the right folders
but not i can't get in the game...
no errors in console, just a loop back saying already logged in, tried to set logged in to 0 in database, no solution
tried locally, and public (ports are open)

i was reading in forums, and im not the only one with this problem on moopledev based sources in v83...
probably the wrong JCE files? i can't tell what's wrong.

**Comment by jaydenseah** [comment]
Have you tried drop SQL and re-extract all SQL again?

**Comment by lucasziron** [comment]
check ip.

**Comment by Arufonsu** [comment]
having only java jdk-7u79-windows-x64 installed and the policy files properly placed, also
recompiled with netbeans using the core files and java 1.7.
then yes, tried with a fresh SQL and the problem persist
about it: tried with 127.0.0.1 and a localhost with 127.0.0.1 and the problem persist so is not a ports problem, which should be not because yesterday i was playing with a friend using my wan ip along with nashorn and java 8... im not saying i like java 8, it has a lot of problems with the scripts you see, i really want to run this under 7! ToT

**Comment by ronancpl** [comment]
You should check if there's any references towards other platforms on the system's path or Java's classpath, since those can make the program behave oddly. On a clean environment system there should be no issues like that when opening the server.

**Comment by Arufonsu** [comment]
im going to try on a clean VM later on, thanks for the suggestion.

**Comment by Arufonsu** [comment]
close this!
tried on a cheap VPS  with windows 7 ultimate x64 and everything works smooth 👍 !
might want to add on readme notes: windows 10 and home series might have problems with java 7

**Comment by ronancpl** [comment]
Hmm, I don't think w10 with Home Basic could be a issue. One of the machines I run the structure runs it finely, using Java 7 by default.
