### ISSUE TITLE
Enter game though "view all characters" window at world select with PIC enabled.

### ISSUE THREAD

**Issue by Arufonsu** [ronancpl/HeavenMS#221]
apparently some vietnamite users like to login by using the view all characters window in world select screen. this with PIC enabled, triggered an error at: 

packethandler/net.server.handlers.login.ViewAllCharSelectedWithPicHandler.txt

the error is easy to reproduce:
-Enable PIC
-Login
-Click view "all characters" and try to Enter game with any character by entering PIC

hope these issues reports help the development, as we are testing the server with people randomly!

**Comment by ronancpl** [comment]
Issue solved.
