### ISSUE TITLE
GM hide needs to be reworked

### ISSUE THREAD

**Issue by Arufonsu** [ronancpl/HeavenMS#222]
as title says, others can see when monsters miss/hit you while using GM Hide, so they try to escape if catched hacking. there was a way to apply dark sight effect for GM Hidde and remove the player from map so that doesn't happens. i used to be able to make it work back in v62 sources, but i can't really figure out here in maplesolaxia source.

The perfect Gm Hide is like: 
-monster's cant touch you "god mode"
-other's won't see the spawn packet, we remove the player from map before that
-other's won't see GM's Miss/1s hits even if invisible

**Comment by ronancpl** [comment]
As far as I've checked, that feature seems to work properly, as shown on the image below:

![image](https://user-images.githubusercontent.com/9257761/42487055-8dcbbd78-83d5-11e8-891c-fe7d98a013e2.png)

**Comment by Arufonsu** [comment]
Ohh.. i didn't knew about the GM client.. thanks haha

**Comment by ronancpl** [comment]
What I meant is, as it currently is, it's not expected to have GM hide issues if no commands are given to the server. If a GM decides to hide in midst of a crowd, they will still see him standing at the last point he was visible to them. In-game, the current way to solve this is simply changing maps or channels.

**Comment by ronancpl** [comment]
Oh, and regarding the "GM client" that seems to have been misinterpreted... From the client-server software architeture view, anything that interacts with the server would be called the "client", around here being the usual localhost.exe.

Needless to say, the GMs and admins usually interacts with the server using localhosts as well, so there's no mistake in calling them "clients" as well, if following this paradigm.
