### ISSUE TITLE
Commotion on the Ship (Quest) - 28210 "Inventory full"

### ISSUE THREAD

**Issue by Arufonsu** [ronancpl/HeavenMS#224]
this quest have a weird check, it says inventory is full on players! no errors on console.
after the players slay the 30 ribbon pigs, they get an "inventory is full" message, and their inventory is not full !

**Comment by ronancpl** [comment]
Got it. It indeed has a weird check, the Act.img expects the player to hand 30 pig ribbon (Etc) on quest completion while the Check.img expects 30 kills... Simply removing the item rule on Act.img for the questid 28208 solves the issue.
