### ISSUE TITLE
Pink Bean drops no items while in Pink Bean Expedition

### ISSUE THREAD

**Issue by UltimateMors** [ronancpl/HeavenMS#227]
Hey. I came back to messing around with v83, and when I was looking at expedition bosses, I noticed something weird with Pink Bean. He drops no items when being defeated.

I tested this four ways: 

The first way was killing him outside of the expedition. He drops items normally.

The second way was killing him while in the expedition and killing him normally while in there. (Killing him after defeating all the statues, just like a normal run.) He drops no items.

The third way was killing him while in the expedition just using the !killall command, which makes him spawn almost instantly, and killing him again with the !killall command. He drops no items.

The final way was spawning him inside of the expedition, then killing him normally with attacks. He drops items normally.

This was the latest build of the source, and is quite clean other than some global drops added, and a few things changed in server constants, making me doubt it has to do with anything on my end. If you need more information, tell me. Thanks.

**Comment by xinyifly** [comment]
Last time I killed pink bean in expedition, also nothing dropped. I thought it was my bad luk. !pinkbean and killing does drop items.

**Comment by ronancpl** [comment]
Issue solved.
