### ISSUE TITLE
Error when creating characters (with PIC enabled?) for the first time.

### ISSUE THREAD

**Issue by UltimateMors** [ronancpl/HeavenMS#228]
Thanks for the fixes, but I noticed a new bug came with the latest update, even when starting fresh, it always appears. A error will be thrown when creating a new character, mainly these files:

net.server.handlers.login.CreateCharHandler

net.server.handlers.login.RegisterPicHandler

and it seems to occur only when having PIC enabled, didn't test it without PIC yet but I might shortly, but the bug is that when a character is created on a new account, it will thrown an error in the console talking about a null pointer error in those two files, and the character will just walk in place until you log back out, go back in, and then you can create a pic normally. This is latest source, and the files I changed are the serverconstants, and mainly my Character.wz due to WZ edits, but I believe I tested this will all clean files. If you need more information, tell me, thanks.

**Comment by ronancpl** [comment]
There was a logic error on the core of the login system, rendering almost every login action server-breaking. Today's update is supposed to solve this issue.
