### ISSUE TITLE
players can use @stat minus(Number) and reset/abuse command

### ISSUE THREAD

**Issue by Arufonsu** [ronancpl/HeavenMS#229]
@stat can use minus(number), like:

@Str -35
@Dex 35

this allows players to freely reset their stats, making the stat reset items useless. i think this command is only supposed to work with + and not with -
for now i might just disable this command in the source.

**Comment by ronancpl** [comment]
Issue solved.

**Comment by Arufonsu** [comment]
awesome! thanks ronan <3
