### ISSUE TITLE
"Stop the wedding" Quest & MapleCharacter:896 

### ISSUE THREAD

**Issue by Arufonsu** [ronancpl/HeavenMS#235]
- Character with the quest "Stop the wedding" (id 2330) enters from map 106021400 to map 106021401 though TD_MC_enterboss1.js (portal) -> (opens NPC 9102100)
- Player returns to map 106021400
- Player tries to return back to 106021401 and nothing happens in portal
- Player is now stuck (channel dispose problem? @dispose doesn't fix the problem...)
- Reloging makes this happen:
http://oi63.tinypic.com/a2bzuc.jpg
- Player now is stuck, can't login and start game back in the stuck character.
- Possible Solutions: 
-- Restart the server (worked).
-- CS in and back: black screen (fail, stuck).
-- Teleport Rock to somewhere else (worked, unstucked player).
-- Block the entrance until new fix: edited TD_MC_enterboss1.js  with
    pi.message("Stop the wedding Quest is not available (for now).");

**Comment by ronancpl** [comment]
Solved. Should the issue happens again, please open a new issue regarding this.
