### ISSUE TITLE
at ServerListRequestHandler and...

### ISSUE THREAD

**Issue by Arufonsu** [ronancpl/HeavenMS#236]
https://www.dropbox.com/s/l1qw7r61e1znfwi/serverlistrequest.png

Well.. im not sure what's triggering this error in console, but seems to be when the player reach the servers page at login screen.

**Comment by vince538** [comment]
You should go inside your source and checkout which line is giving you the error and returning null.
Probably something isn't being loaded well from the database inside characters table so it returns null.

**Comment by ronancpl** [comment]
There was actually an issue with players wearing no equipments provoking null pointer exceptions. To solve that, just check for null on loadCharacterEntryFromDB: 

```
            if(equipped != null) {  // players can have no equipped items at all, ofc
                MapleInventory inv = ret.inventory[MapleInventoryType.EQUIPPED.ordinal()];
                for (Item item : equipped) {
                    inv.addItemFromDB(item);
                }
            }
```
