### ISSUE TITLE
Some quests don't use the Quest Rate or don't give exp at all

### ISSUE THREAD

**Issue by Arufonsu** [ronancpl/HeavenMS#237]
some quests (very rare) like these won't work with the fixed heavenMS quest rates

this happens with happens with endangered mushking empire..
https://bbb.hidden-street.net/quest/victoria-island/endangered-mushking-empire

reproduce error:
- Have a second job and level 30
- Speak to your Job Instructor and acquire the Recommendation Letter - Job Instructor.
- Head over to Mushroom Castle: Mushroom Forest Field.
- Speak to Head Security Officer to hand over the letter.
error: no 6.000 exp is given

Aanother: a player reported that quest 3414 doesn't use the quest rate for EXP, this isn't tested yet.

**Comment by ronancpl** [comment]
This is supposed to be solved now, on today's commit.
