### ISSUE TITLE
Weird login stuck and monsters spawn stopped

### ISSUE THREAD

**Issue by Arufonsu** [ronancpl/HeavenMS#250]
no errors in console, it happened randomly... i couldn't login and a player reported no mobs spawning.

![imagen](https://user-images.githubusercontent.com/17498701/44886869-7820e780-ac9f-11e8-8116-e3f8b0985427.png)

**Comment by asafgb** [comment]
Error's on the Console???

**Comment by Arufonsu** [comment]
no errors in console, seemed like some deadlock and the only solution was to restart the server.

**Comment by ronancpl** [comment]
Issue merged with #316.
