### ISSUE TITLE
Level 3 Dispel crashes the client

### ISSUE THREAD

**Issue by Arufonsu** [ronancpl/HeavenMS#254]
if you are in party and someone dispels you, the game crashes with error 38

**Comment by ronancpl** [comment]
After checking locally here couldn't reproduce the issue, even on the case with 6 on a party. Would it happen on a very specific scenario?

**Comment by Arufonsu** [comment]
Level 3 dispel crashes the client
over that there's no problem, havent tested with level 4
you tested with level 5 and is fine
i tested with level 20 and is fine

**Comment by Arufonsu** [comment]
fixed in commit 227
