### ISSUE TITLE
noSuchMethod: playerDead / playerRevive

### ISSUE THREAD

**Issue by Arufonsu** [ronancpl/HeavenMS#256]
not sure what triggered this one (PlayerDead):
![imagen](https://user-images.githubusercontent.com/17498701/45248686-cb6fe700-b2ea-11e8-84bb-4b592ed334d3.png)

playerRevive (this one happens if player dies during an instance and clicks OK)
![imagen](https://user-images.githubusercontent.com/17498701/45248752-f0188e80-b2eb-11e8-8428-999c4a76dc10.png)

**Comment by ronancpl** [comment]
Methods playerDead / playerRevive are now optional. Issue solved.
