### ISSUE TITLE
Need a proper way to get rid of distance hackers

### ISSUE THREAD

**Issue by Arufonsu** [ronancpl/HeavenMS#264]
There's no proper way to check distance hacks, only a warning without dc / autobans

this picture shows a local test with a dark knight using rush in "Haunted House - Chimney Possessed by the Clown" without hacks
![imagen](https://user-images.githubusercontent.com/17498701/47256854-9fed2a00-d45c-11e8-8292-9f39232f2ed8.png)

in the class AbstractDealDamageHandler:
```
if(distance > distanceToDetect) {
                        AutobanFactory.DISTANCE_HACK.alert(player, "Distance Sq to monster: " + distance + " SID: " + attack.skill + " MID: " + monster.getId());
                    }
```

tried to add autoban in the distance hack check method, but then a bunch of players like the one in the picture (a local test WITHOUT HACKS) were getting banned... **the issue** is that the player attacks and their position are  **inaccurate** on the server side and adding autoban or dc packet to the distance hack check will affect players that use no hacks. so then how can we handle the real hackers? GM patrol seems the only solution as now. someone in discord suggested to have a threshold.. something like 5 alerts in 30 sec to dc the player incurring into distance hacks

**Comment by ronancpl** [comment]
Indeed, for that distance hack check issue, frequency distance checking would be a paliative solution but a good solution in the big picture.

However, unfortunately the HeavenMS development scope should not attend the autoban feature, so this issue will be closed. Sorry for the inconvenience, and thanks for understanding.
