### ISSUE TITLE
[Suggestion] Auto select first channel and last character used

### ISSUE THREAD

**Issue by jnpl95** [ronancpl/HeavenMS#269]
It would be nice if this source had auto select first channel, and auto select last character used (or first character). So that you can just click keep clicking enter until you're ingame. Just a suggestion to add to the source

**Comment by ronancpl** [comment]
Thanks a lot for sharing your suggestion!

Pondered about that for a while, but figured out doing that in practice would be hackish in many ways. The usual login phase, choosing a world, channel and picking a character to play is not that demanding, and keeps the intended GMS-like behavior.

Again, thanks for feedbacking.
