### ISSUE TITLE
Sometimes players level up multiple times

### ISSUE THREAD

**Issue by MedicOP** [ronancpl/HeavenMS#281]
I don't know why and I don't know how to reproduce it, but it has happened multiple times where a player levels up 2 to 3 times in one go while simply grinding, even though the EXP gained from the mobs should have only resulted in 1 levelup.

After this happens, the EXP looks normal, somewhere just over 0% as you would normally expect when leveling up.

Example: Aran is training at jesters. EXP is at 99.9% and kills a few mobs, then goes from level 167 instantly to level 170. In the guild you also see the notification 3 times: Aran has reached level 168, Aran has reached level 169, Aran has reached level 170.

Has anyone experienced anything similar?

**Comment by MedicOP** [comment]
Perhaps MapleCharacter.gainExpInternal should be synchronized?

**Comment by ronancpl** [comment]
Indeed, MapleCharacter.gainExpInternal should get better concurrently protected. But method synchronization isn't an advisable measure to be applied in this case, since there are several internal chores that also locks resources.

**Comment by ronancpl** [comment]
The picking point there is about synchronizing the exp value. I'll be looking into it, thanks for reporting.

**Comment by ronancpl** [comment]
Ok, reconsidered usage of method synchronization. It's actually valid on this case since levelUp already uses this. Once again, thanks for reporting @MedicOP.

**Comment by ronancpl** [comment]
Should this issue appear again, please open another issue referencing this.
