### ISSUE TITLE
Unable to login channel

### ISSUE THREAD

**Issue by AvivLiberman** [ronancpl/HeavenMS#282]
![image](https://user-images.githubusercontent.com/45610501/49661309-65157480-fa51-11e8-99cd-637a51f5822a.png)

I run wireshark and haven't seen any request from ports 7575-7579

**Comment by ronancpl** [comment]
Follow @Masterrulax's solution in the Discord channel, it should solve the problem.

![image](https://user-images.githubusercontent.com/9257761/49664360-d1d04500-fa38-11e8-842b-722605753834.png)

**Comment by AvivLiberman** [comment]
after changing the configuration file it worked. Thanks!!!
