### ISSUE TITLE
Drop rate in MySQL table

### ISSUE THREAD

**Issue by marcuswoon** [ronancpl/HeavenMS#287]
First of all, sorry this is not an "issue", more for understanding purposes. What i understand is the drop rate figure in the MySQL table should be read this way:

Figures in drop rate table / 999,999 x server drop rate x 100 = gameplay drop rate in %

Am I right?

However, i tried testing by putting 999,999 for global item like cash coupon, it doesnt drop 100%.

After that I played around by increasing server drop rate to 20x, then i get 100% drop rate.

Can anyone explain how does the figure in MySQL drop rate works?

**Comment by ronancpl** [comment]
Assuming player drop rate is >= 1, items with drop rate 999,999 by default should drop as if they were 100%.

By chance, have you tried to !reloaddrops after having edited value in MySQL? If not they are still using the same drop chance as before, and your change would only apply after restarting the server.

**Comment by marcuswoon** [comment]
yes i did restart the server by closing everything and start again.

ok will try reloaddrops

thanks and merry christmas

**Comment by ronancpl** [comment]
merry christmas for you as well
