### ISSUE TITLE
Quest at temple of time, to kill 999 monsters

### ISSUE THREAD

**Issue by marcuswoon** [ronancpl/HeavenMS#291]
i noticed the temple of time 999 quest, when initiate, it starts with 922/999 already?
is this being done on purpose?

**Comment by ronancpl** [comment]
It is particularly designed as a server flag for short session gameplays on ToT. Check the ServerConstants.TOT_MOB_QUEST_REQUIREMENT flag value.

**Comment by marcuswoon** [comment]
thank you
