### ISSUE TITLE
can't delete character if filled in PIC in the last 30 minutes

### ISSUE THREAD

**Issue by MedicOP** [ronancpl/HeavenMS#297]
https://media.discordapp.net/attachments/510464999710523392/530194808375869461/unknown.png

When trying to delete the last character on your account, it shows this error unless you wait like 30 minutes until the PIC isn't remembered anymore

**Comment by ronancpl** [comment]
Unfortunately, this is one limitation of the Delete Character feature.

To delete, one's client must provide a PIC. However, to do so, the server sends to the client a byte informing PIC-sending is required (this triggers the PIC popup panel).
A workaround has been done to bypass extra PIN-PIC auth if one already entered their PIN-PIC recently. Noteworthy, bypass PIC means no PIC popup would be available for accounts that have been active recently.

To player regain instant access to PIN/PIC auth: @enableauth
To disable bypass PIC, set server flag: BYPASS_PIC_EXPIRATION = 0
