### ISSUE TITLE
bug after the update.

### ISSUE THREAD

**Issue by lucasziron** [ronancpl/HeavenMS#304]
quests are not updating automatically.
It is necessary to leave the game for the quest to appear.

**Comment by ronancpl** [comment]
I'm not quite sure about the contents of this issue. If you don't mind, could you please provide a few more details about it?

**Comment by ronancpl** [comment]
We discussed a bit after... Main symptoms of this particular issue would be "quests would not appear after changing maps" and "some NPC scripts would not trigger". Issue solved on #305
