### ISSUE TITLE
Buddy find fix

### ISSUE THREAD

**Issue by Atoot** [ronancpl/HeavenMS#308]
\src\net\server\channel\handlers\WhisperHandler.java

        } else if (mode == 0x44) {
            //Buddy find
            String recipient = slea.readMapleAsciiString();
            MapleCharacter player = c.getWorldServer().getPlayerStorage().getCharacterByName(recipient);
            if (player != null && c.getPlayer().gmLevel() >= player.gmLevel()) {
                if (player.getCashShop().isOpened()) {  // in CashShop
                    c.getSession().write(MaplePacketCreator.getFindReplyWithCS(recipient));  
                } else if (player.isAwayFromWorld()) {  // in MTS
                    c.getSession().write(MaplePacketCreator.getFindReplyWithMTS(recipient));   
                } else {
                    c.getSession().write(MaplePacketCreator.getFindReplyWithMap(player.getName(), player.getMap().getId()));
                }        
            }
        }

\src\tools\MaplePacketCreator.java"

        public static byte[] getFindReplyWithMap(String target, int mapid) {
                MaplePacketLittleEndianWriter mplew = new MaplePacketLittleEndianWriter();
                mplew.writeShort(SendOpcode.WHISPER.getValue());
                mplew.write(72);
                mplew.writeMapleAsciiString(target);
                mplew.write(1);
                mplew.writeInt(mapid);
                mplew.writeBytes(8);
                return mplew.getPacket();
        }

        public static byte[] getFindReplyWithCS(String target) {
            MaplePacketLittleEndianWriter mplew = new MaplePacketLittleEndianWriter();
            mplew.writeShort(SendOpcode.WHISPER.getValue());
            mplew.write(72);
            mplew.writeMapleAsciiString(target);
            mplew.write(2);
            mplew.writeInt(-1);
            return mplew.getPacket();
        }

        public static byte[] getFindReplyWithMTS(String target) {
            MaplePacketLittleEndianWriter mplew = new MaplePacketLittleEndianWriter();
            mplew.writeShort(SendOpcode.WHISPER.getValue());
            mplew.write(72);
            mplew.writeMapleAsciiString(target);
            mplew.write(0);
            mplew.writeInt(-1);
            return mplew.getPacket();
        }

\src\tools\data\output\GenericLittleEndianWriter.java

    public final void writeBytes(final int i) {
        for (int x = 0; x < i; x++) {
            bos.writeByte((byte) 0);
        }
    }

**Comment by MedicOP** [comment]
Made it into a PR #311

**Comment by ronancpl** [comment]
Pull Request merged.
