### ISSUE TITLE
Use MCDB Or NX Files Over XMLWZ

### ISSUE THREAD

**Issue by ExtremeDevilz** [ronancpl/HeavenMS#31]
hi, 

the provider that odin used was a bad implementation of wz back in those days of 2008, I would 
suggest using the nx file provider or mcdb. the xml uses too much memory.

http://nxformat.github.io/
https://github.com/diamondo25/mcdb-files/tree/master/mcdb-4.3-global-83

you can test xmlwz vs mcdb vs nx, you will noticed that xmlwz uses up alot of memory.

**Comment by NovaStory** [comment]
**But most do not know how to use the NX unless you have video tutorials**

**Comment by ronancpl** [comment]
Thanks for sharing this piece of information, indeed NX files are such a set of fine improvements on the MapleStory private server scenario.

However, as stated by retep on a thread on RZ: "It's a significant amount of work, not as easy as just 'put[ting] the library in the java build'." As I am about to take a break on further development on this server for the time being, sticking with WZs seems fine for me.

Again, thanks for sharing this info!

**Comment by resinate** [comment]
ronan any plans on trying for a v111 source?

**Comment by ExtremeDevilz** [comment]
@ronancpl

there is a development library but I believe it is old, you can make it your own and maybe people can use it as well, you might want to check out leaftown v83 ;), it will improve the server

**Comment by ronancpl** [comment]
Hmm, no resinate. I intend to just make minor fixes now on this v83 server, if critical issues arises.
