### ISSUE TITLE
Certain NPCs have weird placement

### ISSUE THREAD

**Issue by MedicOP** [ronancpl/HeavenMS#312]
![9cfbb89f9a37695c493cfbb8775231c1](https://user-images.githubusercontent.com/18251099/51007159-b4fec400-1546-11e9-9a3f-4c0aae0eb3ff.png)
![unknown](https://user-images.githubusercontent.com/18251099/51007160-b5975a80-1546-11e9-8184-c304ba143b62.png)

**Comment by ronancpl** [comment]
To solve this issue, reexport XML contents from the wz into the server-side xml folders.
