### ISSUE TITLE
MapleCharacter.getMarriageQuestLevel doesn't exist?

### ISSUE THREAD

**Issue by MedicOP** [ronancpl/HeavenMS#315]
https://github.com/ronancpl/HeavenMS/blob/dac5c436350664c69172c22c70642b8cdbdca7c7/scripts/npc/9201003.js#L46

The method is used in this script but does not exist. addMarriageQuestLevel also doesn't exist

**Comment by ronancpl** [comment]
The current Marriage quest still doesn't take into account this script interaction. Covering this here.

**Comment by ronancpl** [comment]
Updated content.
