### ISSUE TITLE
Cannot change rates

### ISSUE THREAD

**Issue by ynaroth** [ronancpl/HeavenMS#324]
after changing ServerConstant i tried clean + build the source but it didnt work, i tried opening it again as a new source, but it still didnt work... how can i make it work? (i tried what i've read from issues before)

**Comment by ynaroth** [comment]
Thank you! but whats the serverconstant.java exprate for then?

**Comment by ronancpl** [comment]
Implemented boss drop rate and removed fixed rates for world 0 in the default world.ini file.
