### ISSUE TITLE
HP MP auto pot

### ISSUE THREAD

**Issue by marcuswoon** [ronancpl/HeavenMS#325]
in the server constant:

public static final double PET_AUTOHP_RATIO = 0.99
public static final double PET_AUTOMP_RATIO = 0.99

I assumed the settings bar in the game is the trigger point and it will heal up to the ratio set above.

would we be able to set it to follow the settings bar in the game? eg: if it triggers, it will only consume one potion since one is sufficient to increase the HP/MP above the trigger point set.

**Comment by ronancpl** [comment]
That information is client-side, it's not supposed to reach the server, therefore that's not an option.

Yet, if there's an issue with how many pots are being consumed, there's an alternative to set RATIO to 0.01, preventing compulsory consuming, and setting a floor to the "qtyCount" to 1.

**Comment by marcuswoon** [comment]
i noticed if the server side set to a lower value, say 0.1, and if the client bar is at a higher level, it will not trigger auto pot, it will still go down to the ratio of 0.1 before triggering auto pot.

**Comment by ronancpl** [comment]
Implemented flag USE_COMPULSORY_AUTOPOT for this case.
