### ISSUE TITLE
CouponRates

### ISSUE THREAD

**Issue by Atoot** [ronancpl/HeavenMS#329]
The superposition of experience coupons leads to high experience multiplier

server rates 1x
cash shop buy 3X coupons + 2X coupons 
player rates  become 6x
By analogy, the more coupons, the higher the rates...
Hope coupons can't be superimposed.

**Comment by ronancpl** [comment]
The USE_STACK_COUPON_RATES flag is supposed to mitigate this effect when set to false.

In second thought, will take it into consideration for the default settings, since coupons really shouldn't behave this way.

**Comment by ronancpl** [comment]
The USE_STACK_COUPON_RATES flag is supposed to mitigate this effect when set to false.

In second thought, will take it into consideration for the default settings, since coupons really shouldn't behave that way.
