### ISSUE TITLE
Weird aggro behavior

### ISSUE THREAD

**Issue by MedicOP** [ronancpl/HeavenMS#330]
There are some issues with mob aggro that I've noticed when multiple players are in the map.

For example, if you fight Big Foot or The Boss, they always target the same 1 player even if that player isn't attacking/hasn't attacked. 

Another example is Twisted Jesters always follow the same player too, even just after the mobs respawn and the player has never attacked. 

I named those specific monsters as examples, but it could be an issue with all mobs or maybe all ranged mobs

**Comment by ronancpl** [comment]
Currently on it.

**Comment by ronancpl** [comment]
Implemented feature!
