### ISSUE TITLE
Buddy find Channel fix

### ISSUE THREAD

**Issue by Atoot** [ronancpl/HeavenMS#331]
\src\net\server\channel\handlers\WhisperHandler.java

        } else if (mode == 0x44) {
            //Buddy find
            String recipient = slea.readMapleAsciiString();
            MapleCharacter player = c.getWorldServer().getPlayerStorage().getCharacterByName(recipient);
            if (player != null && c.getPlayer().gmLevel() >= player.gmLevel()) {
                if (player.getCashShop().isOpened()) {  // in CashShop
                    c.getSession().write(MaplePacketCreator.getFindReplyWithCS(recipient));
                } else if (player.isAwayFromWorld()) {  // in MTS
                    c.getSession().write(MaplePacketCreator.getFindReplyWithMTS(recipient));
                } else  if (player.getClient().getChannel() != c.getChannel()) {
                    c.getSession().write(MaplePacketCreator.getFindReplyWithCh(recipient, (byte) player.getClient().getChannel()));
                } else {
                    c.getSession().write(MaplePacketCreator.getFindReplyWithMap(player.getName(), player.getMap().getId()));
                }
            }
        }

\src\tools\MaplePacketCreator.java

        public static byte[] getFindReplyWithCh(String target, int channel) {
                MaplePacketLittleEndianWriter mplew = new MaplePacketLittleEndianWriter();
                mplew.writeShort(SendOpcode.WHISPER.getValue());
                mplew.write(72);
                mplew.writeMapleAsciiString(target);
                mplew.write(3);
                mplew.writeInt(channel - 1);
                return mplew.getPacket();
        }

**Comment by MedicOP** [comment]
Made a PR https://github.com/ronancpl/HeavenMS/pull/332

**Comment by ronancpl** [comment]
PR merged.
