### ISSUE TITLE
Monster Magnet skill causes crash error code 38

### ISSUE THREAD

**Issue by MedicOP** [ronancpl/HeavenMS#333]
The Monster Magnet warrior skill causes crash error code 38 for all players in the map any time it is used

**Comment by MedicOP** [comment]
For some reason it not causing DC anymore as of writing this. However, the skill is only visible to the player who uses it and not to others in the map.

**Comment by ronancpl** [comment]
Let me know if you can determine a case of DC'ing by using the skill.

Solving here broadcast visibility of it.

**Comment by ronancpl** [comment]
Should work now, I'm closing this. Please reopen should this issue is still up.
