### ISSUE TITLE
Trade Errror

### ISSUE THREAD

**Issue by lziron** [ronancpl/HeavenMS#341]
when making trade with another character having mesos full (2147483647) the trade and held, and the money is lost. the right thing would be to cancel the exchange, because the character can not receive more mesos.

**Comment by ronancpl** [comment]
Couldn't find a case where mesos are lost after trading with another character.

The current implementation ceils up mesos at Integer.MAX_VALUE (2147483647).

**Comment by lziron** [comment]
the exchange could not happen, because if I have MAX MESOSI can not receive more, the exchange should be canceled.

**Comment by MedicOP** [comment]
I can't speak for NPC shops or player trades, but I know for hired merchants / player shops it is not possible in GMS to buy an item if it would result in the shop owner getting more than max mesos.

**Comment by ronancpl** [comment]
Implemented check.
