### ISSUE TITLE
Rankings aren't sorted by date

### ISSUE THREAD

**Issue by MedicOP** [ronancpl/HeavenMS#343]
The level rankings aren't sorted by date, which I believe they should be.

Someone could be the first to reach level 200, but they could be number 10 in the rankings.

Could add a "lastExpGain" to the characters table and sort by that: ORDER BY level DESC, exp DESC, lastExpGain ASC

**Comment by ronancpl** [comment]
Indeed.

A PR would be welcomed for this patch. A suggestion, since on characters table there is a `lastLogoutTime` variable, `lastExpTime` or `lastExpGainTime` could suit it well, it's up to the PR author.

**Comment by MedicOP** [comment]
I'll make a PR

Btw, the `lastLogoutTime` actually never gets updated
