### ISSUE TITLE
continent

### ISSUE THREAD

**Issue by marcuswoon** [ronancpl/HeavenMS#354]
hi sorry, this is not an issue but could not find where to ask, did a search in the source seems nothing, where can we find what to insert into the continent column at the global drop data for specific continent drops?

**Comment by ronancpl** [comment]
Hi.

That functionality is currently not implemented, as all global entries can be dropped by mobs, therefore there's nowhere in the source to refer about it.

**Comment by marcuswoon** [comment]
alright thank you
