### ISSUE TITLE
Using Hyper Body removes hp/mp

### ISSUE THREAD

**Issue by MedicOP** [ronancpl/HeavenMS#357]
MaxHP without Hyper Body: 1000

Player uses hyper body and a potion to heal up. The player now has 1600/1600 HP

Then the player uses Hyper Body again before it expires.
For some reason the HP is now at 1000/1600 instead of still 1600/1600

**Comment by MedicOP** [comment]
Also I have ServerConstants.USE_FIXED_RATIO_HPMP_UPDATE = false. Not sure if it matters

**Comment by ronancpl** [comment]
Actually, the issue is another. Using HyperBody first deactivates the HB buff before reapplying.

One can see the effect when having HP: 9999/10000 -> HB -> full heal -> HB (again).
HP value after rebuffing becomes MaxHP before using HB.

**Comment by MedicOP** [comment]
Yes that's right, but I believe it only seems to happen with USE_FIXED_RATIO_HPMP_UPDATE set to false

**Comment by ronancpl** [comment]
Well, in a matter of fact I already have a solution for that, although it involves further testings.

At MapleStatEffect, applyBuffEffect():
```
        if (!isMonsterRiding() && !isCouponBuff() && !isMysticDoor() && !isHyperBody()) {     // last mystic door already dispelled if it has been used before.
            applyto.cancelEffect(this, true, -1);
        }
```

If the solution looks reliable for you, you can issue a PR for that.

**Comment by MedicOP** [comment]
https://github.com/ronancpl/HeavenMS/pull/359
