### ISSUE TITLE
Can't redo expeditions

### ISSUE THREAD

**Issue by Arufonsu** [ronancpl/HeavenMS#358]
As title says, players can't do zakum expedition once they do one run

error in console after a group of 3 finished a zakum run and tried to make a new expedition:
![2](https://user-images.githubusercontent.com/17498701/51568160-d54c4e00-1e77-11e9-831a-45bd796be4f0.png)

this is what the npc says, even though there's no expedition inside the map
![1](https://user-images.githubusercontent.com/17498701/51568058-97e7c080-1e77-11e9-9135-f8d57fe9bbb9.png)

**Comment by MedicOP** [comment]
Have also experienced this issue before. Could be related to https://github.com/ronancpl/HeavenMS/issues/334 if one of your expedition members left?

**Comment by Arufonsu** [comment]
similar issue with another NPC
![imagen](https://user-images.githubusercontent.com/17498701/51726601-f44d0a80-2046-11e9-9b5e-c9b37ec2c8d9.png)

**Comment by Arufonsu** [comment]
Fixed by using the latest wz xml files
