### ISSUE TITLE
Weird letters in NPC dialogue box

### ISSUE THREAD

**Issue by Coentje44** [ronancpl/HeavenMS#374]
![maple0001](https://user-images.githubusercontent.com/1202162/51805979-70786580-2274-11e9-809d-afbbf44273cd.jpg)
There's two letters 'n' appearing on every npc dialogue box.
Anyone know how to get rid of them?

**Comment by Coentje44** [comment]
Switched to a different Localhost and that seemed to fix it.

**Comment by ronancpl** [comment]
Sorry for answering just after this issue has been solved.

Yes, the 'n' issue is localhost-related. Sometime ago, Lowsir released a fix for it on rz.
If anyone wants to check it out, it's there: http://forum.ragezone.com/f921/release-bug-fix-1139965/
