### ISSUE TITLE
localhost collapse

### ISSUE THREAD

**Issue by Atoot** [ronancpl/HeavenMS#379]
I find that sometimes the game becomes dull, and the time for changing maps to black screen is too long. BGM is still the same as before. Then the game collapsed. This is the most common situation when you hit Boss. I heard it was caused by a memory leak somewhere. Just drop its NOP.

**Comment by ronancpl** [comment]
Is this something that's supposed to happen only in the long run or you can catch this just after starting the server?

**Comment by Atoot** [comment]
That's what happens after a while. In fact, as long as you hit the boss, you will collapse immediately, such as Zakum.
It seems that memory leak somewhere caused it.

**Comment by Atoot** [comment]
![w_ 6 zljmkcr5 fxaea5wis](https://user-images.githubusercontent.com/26664343/51957083-3205c500-2485-11e9-8ecc-ea01deecb3fa.png)
![e cm 65vj_hkyrflj sajq](https://user-images.githubusercontent.com/26664343/51957095-392cd300-2485-11e9-87be-42cd920cbcf2.png)
![devsb 0s k50 mrtp ix](https://user-images.githubusercontent.com/26664343/51957097-3b8f2d00-2485-11e9-8d48-3d87f099db4c.png)

**Comment by Atoot** [comment]
Changing maps takes a long time, BGM does not switch, the game background becomes messy, and the game program disappears.

**Comment by Atoot** [comment]
http://forum.ragezone.com/f921/xmas-2018-client-edits-1157153/

**Comment by ronancpl** [comment]
Using the recommended localhost is supposed to clear this issue thoroughly...

Now, if you're still up on troubleshooting the localhost issue, I am sorry for the inconvenience, but please use rz to query that problem.

**Comment by Atoot** [comment]
What I use is to recommend localhosts.

**Comment by ronancpl** [comment]
I'm not so sure about the matter, but using the recommended localhost https://hostr.co/m2bVtnizCtmD is supposed to not collapse when playing the game.

That is to say, provided all the stacks are set thoroughly (as depicted on readme), and the minimum machine requirements to run the server AND the client are matched (see https://www.game-debate.com/games/index.php?g_id=455&game=MapleStory).
