### ISSUE TITLE
"The Remnants of Horned Tail" quest

### ISSUE THREAD

**Issue by MedicOP** [ronancpl/HeavenMS#381]
nvm

**Comment by MedicOP** [comment]
There is no issue. It is only possible to access quest 3714 by talking to NPC 2081011 who is located the map 240040612. The portal warps you to 240040611 if you have not finished quest 3706 before, which is the actual quest that gives you the Dragon Stone.

**Comment by ronancpl** [comment]
You are right.

But that served to notice how the quest 3714 should also give players a `2041200 - Dragon Stone`, but it currently doesn't. Since this one is now solved locally, this issue is done over.
