### ISSUE TITLE
horntail issue

### ISSUE THREAD

**Issue by Arufonsu** [ronancpl/HeavenMS#392]
After the commit 283, horntail doesnt drops any item and when defeated it wont trigger the monsterKilled function from the event script. thus it doesn't clears the expedition, the timer doesn't stops, broadcastHorntailVictory is not sent, etc.

**Comment by MedicOP** [comment]
Did you alter your drop_data_global table

**Comment by ronancpl** [comment]
Event script seems to interact well with HT expedition, in the current version.

![image](https://user-images.githubusercontent.com/9257761/52188199-907dcb00-2818-11e9-8f7c-f00a92c32af8.png)

**Comment by ronancpl** [comment]
Could be there some specific case where scripts wouldn't act as intended?

**Comment by Arufonsu** [comment]
@medicOP yes i did updated the drop_data_global table

testing other bosses and its fine, only happening with ht so far

**Comment by ronancpl** [comment]
Reportedly solved after rollbacking one or more local edits that would compromise event scripts.
