### ISSUE TITLE
MapMonitor NPE

### ISSUE THREAD

**Issue by Arufonsu** [ronancpl/HeavenMS#397]
not sure what triggered this, but here's a screenshot, hope this report helps!
![imagen](https://user-images.githubusercontent.com/17498701/52356401-e61dc780-2a12-11e9-8d2e-ebba3f557d8b.png)
using commit 283 of HMS

**Comment by MedicOP** [comment]
was fixed in https://github.com/ronancpl/HeavenMS/commit/46fec675f139abd9b81cbe5e862152c89444cc59#diff-6efc8ce4289a501dcc26fd3248bfc62b

**Comment by ronancpl** [comment]
Fixed. Thanks for reporting!
