### ISSUE TITLE
WZ mismacth [Resloved]

### ISSUE THREAD

**Issue by try2hack** [ronancpl/HeavenMS#405]
current WZ not working. i replaced original WZ with current_WZ .
but localhost.exe error
![image](https://user-images.githubusercontent.com/6427501/53124881-1e82e100-358f-11e9-9413-0ba873aaed89.png)
scr from github master

EDIT:WinServer2016 cannot run but win10 is working.

**Comment by ronancpl** [comment]
Please make sure to use the proper Wz according to the commit count, since it's not supposed to work in cross-versions.

**Comment by ronancpl** [comment]
Commit 203 refers to the latest "released" content, see https://github.com/ronancpl/HeavenMS/releases/tag/rev203 for more info.

**Comment by ronancpl** [comment]
Please keep trying a bit, there are times the localhost doesn't seem to open well.

Alternatively, try to test the localhost.exe locally, as found on https://hostr.co/tsYsQzzV6xT0. The latest edit date is from `Feb 10th` and it's supposed to work finely.

**Comment by ronancpl** [comment]
By the way, from the screenshot it seems you're also trying to download commit203_wz (in contrast with the current_wz stack showing on the opened folder). Wz's are hardly expected to work cross-versions, it may work but some features may show some sort of unexpected malfunction.

To use commit203_wz, see more info about that "release" on https://github.com/ronancpl/HeavenMS/releases/tag/rev203

**Comment by ronancpl** [comment]
Since the title claims to be resolved this issue is to be closed, I suppose? Closing this, please keep in touch if the issue persists.
