### ISSUE TITLE
Proposal: Migrate to Maven / Graddle 

### ISSUE THREAD

**Issue by undefined-sin** [ronancpl/HeavenMS#406]
Migrating to maven will improve how dependencies are managed and making it easier to build the application withou rely on netbeans.

**Comment by Nulliphite** [comment]
While I like gradle/maven more, this isn't entirely dependent on netbeans. 

Netbean uses Apache Ant to build their project, so technically you can run it from the command line or even import the project directly to other IDE of your choice.

**Comment by ronancpl** [comment]
Hi, sorry for the late reply.

After pondering for a while, for this development, which is also oriented for the non-developers, probably it's for the best to keep it free of automatized dependencies management.

(It implies usage of one less external software structure, and people should be able to run this program, at least locally, after following the provided instructions)

Thanks for proposing use of Maven / Graddle though!
