### ISSUE TITLE
Pet Skill issue

### ISSUE THREAD

**Issue by try2hack** [ronancpl/HeavenMS#407]
![pet1](https://user-images.githubusercontent.com/6427501/53241091-2fd50600-36d3-11e9-8315-e26655d86859.jpg)
![pet2](https://user-images.githubusercontent.com/6427501/53241092-306d9c80-36d3-11e9-92cf-079d758e1b47.jpg)
![pet3](https://user-images.githubusercontent.com/6427501/53241093-306d9c80-36d3-11e9-9092-9df7957da7e5.jpg)
Pet skill is lost when transfer pet in same account. not function.
but when transfer back to first char skill is back.

**Comment by vcoc** [comment]
This is not a issue. You forgot to pick up your pet items from your first char. This issue can be closed now.

**Comment by ronancpl** [comment]
Answered by @vcoc. In the second character, pet is not equipped with the specific items that allows one to collect items from an area. Issue closed.
