### ISSUE TITLE
Votes column does not exists in account table in db_database.sql

### ISSUE THREAD

**Issue by pandabyte** [ronancpl/HeavenMS#409]
Despite VotePoints being implemented in MapleClient and GM commands, the default db_database.sql does not create the specific column for it

![image](https://user-images.githubusercontent.com/14182886/53281000-8727b480-376d-11e9-9851-313da77667db.png)
![image](https://user-images.githubusercontent.com/14182886/53281023-da9a0280-376d-11e9-8144-10b6d252e7bd.png)

**Comment by ronancpl** [comment]
Add in a PR the column `"votepoints" int(11) NOT NULL DEFAULT '0'` just after rewardpoints in `accounts` table, this should settle it.
