### ISSUE TITLE
Quest drops not working

### ISSUE THREAD

**Issue by JanexLane** [ronancpl/HeavenMS#417]
Items that activate from quests do not drop, and it seems it does the same for HPQ, the seeds don't drop from the plants.

If you could help me fix this I'd be very grateful <3

**Comment by ronancpl** [comment]
Please follow closely the instructions found under this section on the readme: https://github.com/ronancpl/HeavenMS#installing-the-server

After _running without issues/warnings_ the 3 SQL scripts, you should have in the main DB schema a table `reactordrops` with over 1.1k entries, including entries for the HPQ seeds.

**Comment by JanexLane** [comment]
I followed those rules exactly.

**Comment by JanexLane** [comment]
I have both drop_data and reactordrops and I executed the SQL's in the order instructed to.

**Comment by Nulliphite** [comment]
> 
> 
> I have both drop_data and reactordrops and I executed the SQL's in the order instructed to, however despite this the problem remains.

I'm not getting your problem.

Just checking.. Run this SQL and see what you get: 
` SELECT * FROM heavenms.reactordrops WHERE itemid=4001095 OR itemid=4001096 OR itemid=4001097 OR itemid=4001098 OR itemid=4001099 OR itemid=4001100; `

**Comment by JanexLane** [comment]
[https://api-da.wixmp.com/_api/download/file?downloadToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsImV4cCI6MTU1MTM5NjE1NywiaWF0IjoxNTUxMzk1NTQ3LCJqdGkiOiI1Yzc4NmFlNTQ1OWE2Iiwib2JqIjpudWxsLCJhdWQiOlsidXJuOnNlcnZpY2U6ZmlsZS5kb3dubG9hZCJdLCJwYXlsb2FkIjp7InBhdGgiOiJcL2ZcLzA1YWM4ZTY3LTU5YmYtNGFiMi05ZjkyLTEwZmYyODEwOGVjNlwvZGQweTQ2aS0xYTMyNzE4YS1hMDM0LTQzYWEtOTE1YS0wNjg1MjY1YTI4NjUucG5nIn19.9VADxOSmXq_OFGWZzJuAPDNg7HWU1FkeQR81joCO5M8](url)

Here's a screencap of what happens when I execute that.

Just to clarify, since you said you're not getting my problem:
I executed the drops SQL and I executed it in the correct order.
Despite this, quest activated drops are not working. Not just for reactors, for mobs too.
There ARE drops and reactor drops, just not quest drops or PQ drops related to them

**Comment by Nulliphite** [comment]
> 
> 
> https://sta.sh/013qanfpg6fh
> Here's a screencap of what happens when I execute that.
> 
> Just to clarify, since you said you're not getting my problem:
> I executed the drops SQL and I executed it in the correct order.
> Despite this, quest activated drops are not working. Not just for reactors, for mobs too.
> There ARE drops and reactor drops, just not quest drops or PQ drops related to them

Sorry, I meant I am not having your problem, so it must be a problem only exclusive to you.

But. From your image, it is clear that you do not entries for the seeds in that SQL table. 

Run:
`INSERT INTO heavenms.reactordrops (`reactorid`, `itemid`, `chance`, `questid`) VALUES (9102002, 4001095, 3, -1), (9102003, 4001096, 3, -1), (9102004, 4001097, 3, -1), (9102005, 4001098, 3, -1), (9102006, 4001099, 3, -1), (9102007, 4001100, 3, -1);`
and that should solve your HPQ seeds issue at least. 

Although I suspect that there are more problems to your drops then just this. I would recommend you to rerun all the SQL files. Drop tables if you have to.

**Comment by JanexLane** [comment]
I redid the SQL base completely and it fixed it~
The characters got wiped for it, but it fixed the issue so no one is super upset
Thanks for the help guys~

**Comment by ronancpl** [comment]
No problem.
