### ISSUE TITLE
Scrolls always work.

### ISSUE THREAD

**Issue by SlayerOfAll** [ronancpl/HeavenMS#419]
Heya,

i followed your guide step by step and was able to successful set up a server for a few friends of mine and me. We noticed that scrolls will always work no matter what %, is there a way to change that?

**Comment by ronancpl** [comment]
Hey.

Look up the constants.ServerConstants file, it has a server flag named `SCROLL_CHANCE_RATE` in there. Set it to 1 for the default behavior, then compile the system again.

**Comment by SlayerOfAll** [comment]
I finally found the constants.ServerConstants file ( i was looking in the wrong place) and everything works just as it should, thanks for you help.
