### ISSUE TITLE
Missing APs compared to GMS

### ISSUE THREAD

**Issue by xinyifly** [ronancpl/HeavenMS#420]
A lv200 warrior's AP build usually be like this:
```
STR: 999
DEX: 23
INT: 4
LUK: 4
```

In current source, 9 AP is missing from new beginner's creating, 5 AP is missing from 3rd job advancement. (4th job advancement gives 5 AP correctly)

Not sure total AP about Cygnus or Aran.

MapleCharacter.getDefault() shows that initial AP should be 25 in total:
```
ret.str = 12;
ret.dex = 5;
ret.int_ = 4;
ret.luk = 4;
```
CharacterFactoryRecipe has a different initial value:
```
private int str = 4, dex = 4, int_ = 4, luk = 4;
```

**Comment by ronancpl** [comment]
The 3rd job advancement AP is in fact missing and will be checked up.

In the earlier versions of GMS, every player would start up with `4 points in each attribute`, thus this should be a feature at least for when players are allowed to assign their own stats on the starting beginner levels.

12/5/4/4 may still be applicable for when not using the "earlier-GMS mimic" feature (that is, when `USE_AUTOASSIGN_STARTERS_AP` is disabled - a behavior existent on GMS v83), this way matching the build pattern for Warrior above.

**Comment by ronancpl** [comment]
It's being considered to add a bonus __2/3/4 AP__ for _2nd to 4th job advancements_ for when `USE_AUTOASSIGN_STARTERS_AP = false`, so that it helps self-assigning mechanic to also cover the depicted Warrior build, but that will only be done in practice if enough feedback is achieved.

Anyone in agreement or discordance with this move may show up their opinion on this feature by reacting with a :+1: or :-1:, respectively, on this topic.

**Comment by xinyifly** [comment]
@ronancpl Hi, I noticed the `USE_AUTOASSIGN_STARTERS_AP` . The only confusing towards new beginner is that my new created char lost 9 AP that should be in remaining.
It's supposed to be:
```
4/4/4/4
Unallocated: 9
```
But currently it's:
```
4/4/4/4
Unallocated: 0
```
In earlier version of GMS, we can roll a dice, so I think we shouldn't have a pure `4/4/4/4` stat without any extra AP at level 1 (Feeling much weaker cri). Currently I added `recipe.setRemainingAp(9)` in `BeginnerCreator.createRecipe()` in my fork.

**Comment by ronancpl** [comment]
Even before having dice available (v62 if I'm not wrong has that feature), on earlier GMS every character would start the game in this stat factor of 4/4/4/4, AP at 0.

That flag tries to mimic this earlier mechanic, on where players were free to up stats before level 10, and the early game was more challenging (Orange Mushrooms were actually one big threat on the early-game, and would be more challenging on non-STR players).

The way it seems to be on v83 (12/5/4/4), besides the autoassigning that helps players not to naively up dull stats, doesn't seem to be that challenging.

Suppose a player ups HP/MP all the way up when they're given that ability early-game, they'd be penalized by the game by not actually being able to pick a job since they don't fulfill any criteria. That used to be a thing back then, and this flag, when disabled, tries to fulfill that.

**Comment by xinyifly** [comment]
@ronancpl That was the old time mages hit snails (green) to lv8 hahahaha. (It's balanced, tho. After tough beginner time, mages became OP during first job advancement) My confuse solved, thank you.

**Comment by ronancpl** [comment]
@xinyifly Well, seeing the problem that sourced this issue is still up, to settle it up 2 things will be done in development:
- Get the 12/5/4/4 base stats on `USE_AUTOASSIGN_STARTERS_AP = true`;
- Fix the missing AP's on 3rd job advancement;

**Comment by xinyifly** [comment]
@ronancpl Great! And I found that you can check if you're missing AP using a AP Reset checking that if you are able to decrease HP/MP

**Comment by ronancpl** [comment]
Sorry, couldn't understand your statement of using AP Reset to check out missing APs.

AP removal of HP/MP seems to be only related to the minimum base value expected for a player level, possibly unrelated to whether him/her has AP missing or not.

**Comment by xinyifly** [comment]
@ronancpl Assume a situation: modify a normal character's HP/MP into 30k, and try to use an AP Reset. You should be albe to decrease HP/MP. Then modify database to give user some extra APs. With user's total AP increasing, we'll find that the decrease button of HP/MP goes grey once 14 AP(9 in lv1 + 5 in 3rd job advance) added back to character.

**Comment by ronancpl** [comment]
Understood now that metric, thanks for showing it.

But now there's this:

![image](https://user-images.githubusercontent.com/9257761/54073503-9c6d0a80-4266-11e9-879e-4241e0e926ec.png)

![image](https://user-images.githubusercontent.com/9257761/54073451-033df400-4266-11e9-9ca3-05aec9d99a6a.png)

From the images above, warriors at level 200 stops being able to convert HP/MP when `981/23` is reached. STR at 981 occurs when the player was given 1 AP more besides the 995 AP they are supposed to be given.

This may signal players are not intended to be given any more AP than the 995 from levels in a `4/4/4/4` base scenario.

**Comment by xinyifly** [comment]
@ronancpl Did you try advance your job to a 4th job like Hero?

**Comment by ronancpl** [comment]
@xinyifly Oops, actually didn't, my bad.

![image](https://user-images.githubusercontent.com/9257761/54085655-18c32480-431f-11e9-8517-ea1090e90eb0.png)

When trying on a 4th job class, it expects 15 AP more before blocking again. Supposedly, each job change starting from the 2nd is expected to give APs, so it seems.

**Comment by xinyifly** [comment]
@ronancpl Sorry for the late replies, was in traveling and finally got a chance to access Maple client. Here are a serials of Screenshots that for the detailed AP build from AP Reset.

At level 1, with `4/4/4/4 + 8`
<img width="401" alt="MapleForest-STAGE-WINDOW_cWkPknBAvs" src="https://user-images.githubusercontent.com/16129465/54100030-614e1100-43f7-11e9-9634-ade1d232d73d.png">

`4/4/4/4 + 9`
<img width="401" alt="MapleForest-STAGE-WINDOW_pXEKBXK7NT" src="https://user-images.githubusercontent.com/16129465/54100072-8e9abf00-43f7-11e9-90f5-17b8cf579cf3.png">

Go straight level 70 (2nd job advance)
<img width="401" alt="MapleForest-STAGE-WINDOW_Xo4MAwIHW3" src="https://user-images.githubusercontent.com/16129465/54100187-36b08800-43f8-11e9-9088-7f54a2714385.png">

Decrease 1 STR to prove it was correct build
<img width="401" alt="MapleForest-STAGE-WINDOW_ngukLcJWpf" src="https://user-images.githubusercontent.com/16129465/54100215-56e04700-43f8-11e9-9715-bd42ff57fb7a.png">

Level 70, 3rd job advance
<img width="401" alt="MapleForest-STAGE-WINDOW_7DLeo00n0g" src="https://user-images.githubusercontent.com/16129465/54100282-bb9ba180-43f8-11e9-8f4d-17cd97c06b8d.png">

Decrease 1 remaining AP to prove it was correct build
<img width="401" alt="MapleForest-STAGE-WINDOW_Or4bvQpuL8" src="https://user-images.githubusercontent.com/16129465/54100298-c81ffa00-43f8-11e9-89e8-66e0c29f25be.png">

Level 120, 3rd job advance
<img width="401" alt="MapleForest-STAGE-WINDOW_22hAKtrrSD" src="https://user-images.githubusercontent.com/16129465/54100366-1208e000-43f9-11e9-8682-c9ce633ece44.png">

Decrease 1 STR to prove it was correct build
<img width="401" alt="MapleForest-STAGE-WINDOW_WsHBDbBRko" src="https://user-images.githubusercontent.com/16129465/54100383-1df4a200-43f9-11e9-86d3-22478696a508.png">

Level 120, 4th job advance
<img width="401" alt="MapleForest-STAGE-WINDOW_dyj2AIBNTB" src="https://user-images.githubusercontent.com/16129465/54100406-34026280-43f9-11e9-8eb4-0a09aa1219a0.png">

Decrease 1 remaining AP to prove it was correct build
<img width="401" alt="MapleForest-STAGE-WINDOW_2UPF4K9fMF" src="https://user-images.githubusercontent.com/16129465/54100422-47153280-43f9-11e9-8f73-15244187005f.png">

Level 200
<img width="401" alt="MapleForest-STAGE-WINDOW_S3rdumo6pV" src="https://user-images.githubusercontent.com/16129465/54100445-5f854d00-43f9-11e9-9605-b745fff29b32.png">

Decrease 1 DEX to prove it was correct build
<img width="401" alt="MapleForest-STAGE-WINDOW_jE1b1a9hRM" src="https://user-images.githubusercontent.com/16129465/54100453-6c09a580-43f9-11e9-95b8-1029d2cba87b.png">

For the AP build provided in your screenshot
<img width="401" alt="MapleForest-STAGE-WINDOW_KS4FRTTvmd" src="https://user-images.githubusercontent.com/16129465/54100491-952a3600-43f9-11e9-91b6-04f568766180.png">

And with 1 remaining AP decreased
<img width="401" alt="MapleForest-STAGE-WINDOW_aGimqFFTmW" src="https://user-images.githubusercontent.com/16129465/54100507-a96e3300-43f9-11e9-8081-cd247ea03c29.png">

It seems that you didn't count remaining AP in and your total AP actually got exceed.
<img width="401" alt="MapleForest-STAGE-WINDOW_Mfydul1yG0" src="https://user-images.githubusercontent.com/16129465/54100546-e63a2a00-43f9-11e9-91bf-5758edad3095.png">

Online 8 days 🎉
