### ISSUE TITLE
Bonus 2/3/4 AP on job advancements to cover missing AP's

### ISSUE THREAD

**Issue by ronancpl** [ronancpl/HeavenMS#422]
Following the deliberations on #420 about the base _4/4/4/4 AP plus gains_ not matching up with the build below by **9 AP margin**:

![image](https://user-images.githubusercontent.com/9257761/53537494-ecbace80-3ae8-11e9-9ca2-8d74113eeddb.png)

AP gains on explorers:
- 5 AP x 199 levelups = 995 AP
- 10 AP, distributed on __3rd and 4th__ job advancements.

AP spent on 4/4/4/4 build:
- 995 on STR
- 19 on DEX

It is being considered the usage of a bonus **2/3/4 AP** for _2nd to 4th job advancements_ to cover the depicted Warrior build, _only appliable_ when `
USE_AUTOASSIGN_STARTERS_AP = false`, but that will only be done in practice after voting contingency.

Anyone in agreement or discordance with this move may show up their opinion on this feature by reacting with a 👍 or 👎, respectively, on this topic. This will determine whether this addition should be implemented or not on this development.

**Comment by MedicOP** [comment]
Why not just have characters start level 1 with 9 unused AP?

**Comment by ronancpl** [comment]
Well, following up more deliberations on #420 it turns out pointless to keep up with this adjustment... Thank you guys for voting.

It was actually needed, for the explorer case, to simply add 5 AP gain at 2nd to 4th job advancements, using the AP Reset metric taught by @xinyifly, although it's expected to stop at `995 STR/23` rather than `999/23`.
