### ISSUE TITLE
various party quest issues

### ISSUE THREAD

**Issue by seth1** [ronancpl/HeavenMS#430]
taken from Chloek3#8197 of discord

> Hello, I was told to put these here:
> 
> For PPQ: 
> You're not supposed to have to break all the boxes to be able to access the next stages
> You're not supposed to have to click the NPC on stage two for a respawn of the same mob
> I havent went into the doors yet, so I cant say anything about that
> 
> For OPQ: leader entering a level is supposed to teleport the whole party to that level
> On the On the way up stage, you're supposed to teleport up, not this fading thing that doesnt teleport you to the first platform above it when it's the right one
> Also, when you get one wrong, you're not supposed to respawn all the way down, just to the nearest big platform.
> Also I think the timer is going down too fast but I havent actually checked.
> 
> For EPQ: the portal stage is supposed to teleport, too, not this fading thing, but that's minor
> We're also supposed to get altair fragments for every PQ so we can get the earrings.
> 
> Alright so for RnJPQ When you give the letter to juliet in 4th stage, the last boss is supposed to be angry. In 5th stage you're supposed to be able to sneak on yulete to get the boss to be enraged: the npc isnt even in the room, so you cant sneak on it. The 6th stage is the most fucked up. The combination of each party member is supposed to be linked. For each floor, you have 4 platforms (left to right 1 2 3 4): If one party member's combination starts with 1, the other party members cant have 1 as their first number. so if person A has 1, person B has 2 and person C has 3, person D knows that their number is 4. That makes this stage a lot faster to go through and you can help party members find out their combinations when you're done with yours. Also, it's coded has a fade and teleports on the platform above (if your code was 3, you spawn on the platform 3 above it) while it's supposed to be a teleport to the platform on the very left (1) above. How it's coded makes it very confusing to keep track of your own combination

**Comment by ronancpl** [comment]
PPQ suggestions have been implemented now.

**Comment by ronancpl** [comment]
PQ platform issues have been addressed, RnJPQ "Lab Unit" stages now use linked combinations. Thanks for the feedback!
