### ISSUE TITLE
Skill book image missing for beginners

### ISSUE THREAD

**Issue by ryantpayton** [ronancpl/HeavenMS#431]
Not sure if this is a MapleStory issue or not but after completing Roger's Apple quest you gain a level and your skill window automatically pops up. You'll see "Beginner's Basics" with an image next to it that says "Skill Book". Close the automatically opened and tab and re-open your skills window.

You'll see that there is now an image of an actual book and the text is hidden. Might be a bug or just a MapleStory bug but thought I would put it out there!

**Comment by ronancpl** [comment]
This seems like a simple visual bug from MS v83. Since this repository objective is about tackling out only the server-side perspective (or maybe major bugs on the gameplay side), this issue will be ignored and closed. Thank you for showing it up!
