### ISSUE TITLE
Client Disconnect

### ISSUE THREAD

**Issue by ryantpayton** [ronancpl/HeavenMS#432]
If you press the "Back" button on the world selection screen, you get disconnected from the client. Not sure if this is just me or not but it is happening every time for me.

**Comment by ronancpl** [comment]
This doesn't seem to be an issue as so far as tests have gone here. Does it flow ok for you when testing locally?

**Comment by ronancpl** [comment]
This should not be an ongoing issue. Please reopen should the problem persists.

**Comment by ryantpayton** [comment]
Sorry Ronan I am still getting this issue. I didn't see you reply to this.

I'm not sure what you mean by, "Does it flow ok for you when testing locally?".

I am testing with my current live server over WLAN, with port forwarding.

**Comment by ronancpl** [comment]
Try running your current server setup on a loopback IP (`configuration.ini HOST:` 127.0.0.1), and try to login using loopback again and test this problem. Does it still persist?

This test should rule out some of the current cases.

**Comment by ryantpayton** [comment]
Nope! Issue is gone. Although, if that's the case. How do I fix this for running over IP and port-forwarded? Any ideas?

**Comment by ronancpl** [comment]
Hmm, nothing so fancy... Far I can go into ideas is to check for all opened ports using Open Port checker website tools and check if you're properly allowing inbound/outbound data traffic through all used ports on your installed firewall/antivirus.

**Comment by ryantpayton** [comment]
Hmm, okay well thanks for the advice. I'll try and check it out more later. It's not a huge issue.
