### ISSUE TITLE
Multiple mob revives?

### ISSUE THREAD

**Issue by Masaaku** [ronancpl/HeavenMS#436]
It appears mobs that utilize the "revive" node in the WZ spawn double of that mob when killed. I've tried fixing the issue myself (I'm pretty much a noob) to no avail... any tips?

(Ex: Normally, Yeti & Pepe when defeated spawn 1 Yeti and 1 Pepe separately. It seems in this source, 2 Yetis and 2 Pepes spawn upon defeating "Yeti & Pepe.")

**Comment by ronancpl** [comment]
Hmm, not sure which steps you've gone through, but there's no such issue here... No duplicate mobs seem to be spawned upon death. At least for mobid `7130102` and `9500133` it seems ok.

**Comment by ronancpl** [comment]
This should not be an issue. Please reopen should the problem persists.
