### ISSUE TITLE
Cashshop BUG?

### ISSUE THREAD

**Issue by yolinlin** [ronancpl/HeavenMS#439]
Today update the  311,out cashshop is black screen DC！

**Comment by yolinlin** [comment]
不会英语，用中文复述一遍
今天更新了之后，当你从商城出来就会黑屏。

**Comment by ronancpl** [comment]
这个问题现在应该被清除，我非常感谢你的快速报道！

我目前正在使用谷歌翻译器回答你，所以请原谅任何书面不幸。 英语也不是我的母语，但是为了接触大多数人，我正在使用那种语言。 如果需要进一步沟通，请使用该语言。

**Comment by yolinlin** [comment]
很感谢及时更新
