### ISSUE TITLE
083 client problem

### ISSUE THREAD

**Issue by yolinlin** [ronancpl/HeavenMS#440]
当我添加了自定义地图,怪物,NPC时,游戏会出现BUG,地图显示不完全,DC的情况!不知道是不是server的问题?但是在v117上不会出现这个情况.

我非常喜欢custom map!and custom Eqp!

[https://imgchr.com/i/A0UAVs](url)

**Comment by yolinlin** [comment]
刚进游戏并不会这样,在挑战大型BOSS(PB,Dark Dragon)and change map,会加速这个问题的出现,

不知道这样表述能不能理解,但是这对我来说是一个很致命的错误.

**Comment by ronancpl** [comment]
Please consider using the Issues list to report issues related to the current server source in this repository. Custom contents should not be looked on here.
