### ISSUE TITLE
damage reflect spam

### ISSUE THREAD

**Issue by OishiiKawaiiDesu** [ronancpl/HeavenMS#443]
pink bean is impossible to kill it keeps spamming the damage reflect skill
i saw this on ragezone maybe? http://forum.ragezone.com/f427/effect-delay-mob-skills-1078783/ im not coder though

**Comment by ronancpl** [comment]
Indeed, cooldown time is not being properly checked as of currently... Issue identified, your report is most appreciated!

**Comment by ronancpl** [comment]
Mob skills now properly use the cooldown. Please reopen if the issue persists.

**Comment by OishiiKawaiiDesu** [comment]
its not doing the damage reflect so often anymore but it still keeps doing the animation like its about to do it
