### ISSUE TITLE
Party loot problem

### ISSUE THREAD

**Issue by nozphex** [ronancpl/HeavenMS#444]
From last update **"Exp-party" Pi + Event script disabled on dispose + Personal loot fix** 
Just if you are in party alone or with someone if you kill something the item can not be picked up after a long time.

**Comment by ronancpl** [comment]
Well, if it isn't that an odd scenario which would actually show up after passing test phases...

It seems that tests with similar values between the fields option have been fed and passed thoroughly, but fell short on other situations...

Thanks for reporting the issue!

**Comment by ronancpl** [comment]
Patched. Please reopen this issue if the problem still persists.
