### ISSUE TITLE
pink bean keeps doing damage reflect animation

### ISSUE THREAD

**Issue by OishiiKawaiiDesu** [ronancpl/HeavenMS#447]
https://github.com/ronancpl/HeavenMS/issues/443
u fixed that it keeps doing damage reflect but it still shows pinkbean doing the animation but then it doesnt actually do the skill half of the time

**Comment by ronancpl** [comment]
Hey @OishiiKawaiiDesu, please don't worry. The removal of the damage reflect animation will be fixed shortly, sorry for the lateness. Again, your feedback was very appreciated!
