### ISSUE TITLE
Cygnus character that reaches lvl 200 is set to 120 in DB

### ISSUE THREAD

**Issue by CanIGetaPR** [ronancpl/HeavenMS#453]
If someone has a server where cygnus can reach lvl 200, the players level will get reset back to 120 when they are saved.

Why is the max character level even being hard coded in the save to db call? It's not the save method's responsibility to know or decide any limits, it should just save the data without thinking.

https://github.com/ronancpl/HeavenMS/blob/b6a91c523fae668eb785c2fb61933a4ebe862bc3/src/client/MapleCharacter.java#L7973

**Comment by ronancpl** [comment]
Indeed, this should not be a delegation for the saveCharToDB() method. Appreciate your feedback.
