### ISSUE TITLE
Guild not work

### ISSUE THREAD

**Issue by NovaStory** [ronancpl/HeavenMS#465]
When creating in Guild I get an error that I can not create, a help oh what can be done there?

**Comment by jaydenseah** [comment]
Any .bat error?

**Comment by ronancpl** [comment]
All possible message errors you get from trying to create a guild should have info specified about what happened to not being able to create the guild. Check it out and try again.

Alternatively, you may want to display here the error you came across.

**Comment by NovaStory** [comment]
This is the NPC that does not work for me: 
https://i.imgur.com/LI2Smuz.jpg

And when creating the name
https://i.imgur.com/Vq66Iw8.jpg

I get this error?
https://i.imgur.com/oVo1ZI5.jpg

Error in the .bat does not come out, That's why I'm saying that I get an error only in the game but not in the .bat

And the settings I left as they are doing
https://i.imgur.com/1zENeTS.jpg

**Comment by ronancpl** [comment]
That message means you don't have enough players to cover up a guild creation. From the default, and how it currently is in your settings as well, you need to have at least 6 players in the Guild HQ in order to perform a guild creation.

**Comment by NovaStory** [comment]
So, the change in the Guild PQ ?

**Comment by ronancpl** [comment]
Guild Headquarters my man.
