### ISSUE TITLE
Hello to the developer

### ISSUE THREAD

**Issue by maple006** [ronancpl/HeavenMS#468]
Hello, I am just a tester for your project.
Then I informed the problem that I found the error for the developer to improve.
I don't understand why My posts are deleted.
I am just an ordinary member who wants to see Your project continues. I just want to have a collective helping the project.
Sorry for my language

**Comment by jaydenseah** [comment]
Your posted problem has resolved, that's why it's closed now.

**Comment by maple006** [comment]
Thank You

**Comment by ronancpl** [comment]
I can confirm that, your issue has been solved and will show up next update.

**Comment by maple006** [comment]
Thank You

**Comment by ronancpl** [comment]
Don't worry, I'm glad to receive such issue reports!

By myself, I wouldn't be able to even glimpse a lot of issues that I only get to know thanks to people like you who post them here. As a full-stack developer myself, it's an honor to receive those to get to know/learn about shortcomings that may happen during software development and then, from the gathered info, propose solutions to them if possible.
