### ISSUE TITLE
Storage store issue

### ISSUE THREAD

**Issue by BHB88** [ronancpl/HeavenMS#469]
There is an issue with storing bundled items such as scrolls, pots etc.

- Storage is not processing correct quanitity.
- Therefore items are going missing or being duped upon taking items out.

One of many scenarios to reproduce this issue:
- Gain 50 Scroll for Dagger for ATT
- Store 2 scrolls
- Relog or enter CS
- Player will see 2 scrolls in storage and 2 scrolls in inventory
- Gain 50 Scroll for Dagger for ATT
- Player will see 50 scrolls in storage

This issue occured following the recent storage's item store dupe 'fix',

**Comment by ronancpl** [comment]
An object reference issue leading into this... Thanks for reporting!
