### ISSUE TITLE
trade check for rechargeable items

### ISSUE THREAD

**Issue by BHB88** [ronancpl/HeavenMS#473]
A rare scenario where receiving character in a trade has 1 USE slot and is traded 2 rechargeable items. The trade will go through with 1 rechargeable item being lost in the transaction.

Message is displayed at bottom right saying "you can't get anymore items".

Also occurs with 3 items in trade and only have 2 slots.. etc.

**Comment by ronancpl** [comment]
This issue should be clear now, thanks for reporting!

**Comment by BHB88** [comment]
Fixed!
