### ISSUE TITLE
Deadlocks

### ISSUE THREAD

**Issue by davidlafriniere** [ronancpl/HeavenMS#475]
I've attempted to track down and fix the problem myself. The first set of deadlocks seem to have something to do with buffs? I was testing with another player and it seems my GM buffs, wore off as he was transitioning through a portal and it caused a deadlock.

The second deadlock occurred again when he was entering a portal.

Each file is labeled with a date to distinguish the occurrences. 
[Locks_05282019.txt](https://github.com/ronancpl/HeavenMS/files/3247797/Locks_05282019.txt)
[Locks_06032019.txt](https://github.com/ronancpl/HeavenMS/files/3247798/Locks_06032019.txt)
[Path_05282019.txt](https://github.com/ronancpl/HeavenMS/files/3247799/Path_05282019.txt)
[Path_06032019.txt](https://github.com/ronancpl/HeavenMS/files/3247800/Path_06032019.txt)

**Comment by jongames** [comment]
I recently noticed this too.  @buffme has not caused this for me BUT @empowerme command causes this behavior.  It always occurs with using @empowerme followed by !goto (any town).  !warpto (playername) also results in this issue.

It also sometimes occurred with boss map portals / event maps for me so far.

**Comment by ronancpl** [comment]
Noticed a deadlock pattern in those logs:

```
----------------------------
28-05-2019 07:08:34
    CHARACTER_EFF CHARACTER_CHR 

----------------------------
28-05-2019 07:08:34
    PORTAL CHARACTER_CHR CHARACTER_CHR CHARACTER_EFF 
```

Both try to access locks in a different order, causing deadlock.

**Comment by ronancpl** [comment]
This deadlock case has now been cleared. There was a deadlock issue within the recently implemented `updateBuffEffects`. Thanks for reporting!
