### ISSUE TITLE
error deadlock

### ISSUE THREAD

**Issue by maple006** [ronancpl/HeavenMS#476]
This symptom is very frequent.
Did you know Because of what causes

Path.txt
sun.misc.Unsafe.park(Native Method)
    java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
    java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
    java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:867)
    java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1197)
    java.util.concurrent.locks.ReentrantLock$FairSync.lock(ReentrantLock.java:229)
    java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:290)
    net.server.audit.locks.active.TrackerReentrantLock.lock(TrackerReentrantLock.java:77)
    client.MapleCharacter$7.run(MapleCharacter.java:2843)
    server.TimerManager$LoggingSaveRunnable.run(TimerManager.java:148)
    java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
    java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    java.lang.Thread.run(Thread.java:745)

Locks.txt
----------------------------
05-06-2019 16:20:20
    CHARACTER_EFF CHARACTER_CHR 
---------------------------------
----------------------------
05-06-2019 16:20:20
    CHARACTER_CHR 
---------------------------------
----------------------------
05-06-2019 16:20:20
    CHARACTER_EFF 
---------------------------------
----------------------------
05-06-2019 16:20:20
    CHARACTER_CHR CHARACTER_CHR CHARACTER_EFF

**Comment by ronancpl** [comment]
@maple006 Thanks for reporting in this issue.

```
05-06-2019 16:20:20
CHARACTER_EFF CHARACTER_CHR
```

```
05-06-2019 16:20:20
CHARACTER_CHR CHARACTER_CHR CHARACTER_EFF
```

This would be the picture of a deadlock. Notice how in one of the scenarios, CHARACTER_EFF is gathered before CHARACTER_CHR, in the other CHARACTER_CHR is done before CHARACTER_EFF. This pattern can configure a deadlock at some point.

**Comment by maple006** [comment]
Thank you

**Comment by ronancpl** [comment]
Patched. Once again, thanks for reporting!
