### ISSUE TITLE
Mounts

### ISSUE THREAD

**Issue by davidlafriniere** [ronancpl/HeavenMS#479]
Changing maps while on a mount will completely deactivate the buffs effects. When you appear on the next map you'll be on the mount, the buff icon will still be there (although, you can click it to deactivate it), but it's acting as if the buff isn't active. (No speed or jump boosts.) And you can only dismount by changing channels, relogging, or entering the CS and exiting. (To which you'll just appear on the map dismounted.)

The mount works fine otherwise. You can mount and dismount completely fine, the buff activates and deactivates, no problem. Just after you change maps.

[Note: This was tested on a clean source & WZ XMLs, clean WZ files, and clean localhost]

**Comment by ronancpl** [comment]
Ok, thanks for reporting!

By the looks of it, it seems that problem has been already addressed (locally) after patching the recent buff update issues. Since this case seems to be already solved, I will close this. Should, after the next update this issue seem to persist, kindly reopen this.

**Comment by davidlafriniere** [comment]
Thank you, Ronan! ❤
