### ISSUE TITLE
Autoregister not working?

### ISSUE THREAD

**Issue by yuusiren** [ronancpl/HeavenMS#483]
Hi! I'm able to start up the client but unable to login. When I try to login with the accounts that I've created, it either says "Incorrect password" or "Incorrect LOGIN ID". I have done all the steps from the start to the end of "Installing the CLIENT".  Can anyone help me with this issue?

**Comment by xinyifly** [comment]
You may need to post more detailed information to get help here.

For example, the console log during your trying to login, the table definition of your `accounts` table, and the accurate git commit version.

To get a real time support, you may want to join the discord channel in README. https://discord.gg/Q7wKxHX

**Comment by ronancpl** [comment]
Hi, apologies for the late reply. Well, autoregister should be an already working component, already available in the default settings.

Alternatively, if you're creating the account through the SQL browser, make sure the account you just created is in the `accounts` table, when running the query `SELECT * FROM accounts a;`.
