### ISSUE TITLE
CPQ1  battlefield3，4 problem

### ISSUE THREAD

**Issue by Atoot** [ronancpl/HeavenMS#484]
After the death of the player, the battlefield returned is not the original battlefield.Then you will find that even if there is no summoner in the battlefield, when you use F1-F12, you will be prompted to exist.
There is still a 3 minute countdown after the end of the battle

This issue occurs in CPQ1 Battlefield 3 Battlefield 4

**Comment by ronancpl** [comment]
Hmm, it looks like this issue happens after an unexpected "extended time" occurs.

Use case found was one team went to the "resurrection" area, while the other remains on the field. Time is extended (even though the points doesn't equal), and then, after the normal 10-minute timer expires, the players outside of the battlefield reaccess the area.

In result, both teams are on the same map, the battlefield, although neither seems to be able to use summons/protectors. Maybe this would be an issue for all areas?

At any rate, it seems the irregular "timer extended " event needs to be addressed.

**Comment by ronancpl** [comment]
Well, actually a few more tests into this actually tells the summons/protectors does seem to work on those battlefields (CPQ1 Battlefield 3 Battlefield 4).

**Comment by Atoot** [comment]
> Hmm, it looks like this issue happens after an unexpected "extended time" occurs.
> 
> Use case found was one team went to the "resurrection" area, while the other remains on the field. Time is extended (even though the points doesn't equal), and then, after the normal 10-minute timer expires, the players outside of the battlefield reaccess the area.
> 
> In result, both teams are on the same map, the battlefield, although neither seems to be able to use summons/protectors. Maybe this would be an issue for all areas?
> 
> At any rate, it seems the irregular "timer extended " event needs to be addressed.

In fact, when you come out of the "resurrection" area, you will find that the battlefield is not the same, and you will not see the enemy members.

**Comment by ronancpl** [comment]
Hmm, sorry but that issue no longer seems to be occurring. Test case here was one player each team (`USE_ENABLE_SOLO_EXPEDITIONS = true`), of the same level, the dying player reaccess the battlefield seemingly without issues.

In function `getWarpMap(int map)`, this rule is what leads the player back to the battlefield: `warpMap = this.getMonsterCarnival().getEventMap();`
