### ISSUE TITLE
HPQ Moon bunny does not give cake.

### ISSUE THREAD

**Issue by wlsghks540** [ronancpl/HeavenMS#490]
Hi.
HPQ Moon bunny does not give cake. How do I fix it? .. I registered sql database, drops, shopupdate.
I'm sorry I lack English skills

**Comment by ronancpl** [comment]
Hi @wlsghks540, sorry for the late reply.

Is this still an issue? From what it seems, HPQ Moon Bunny drops cake without issues. This is from testing the system freshly booted.

**Comment by wlsghks540** [comment]
Hi. I downloaded it again and applied it. Works fine.
thx!!!!
