### ISSUE TITLE
Gaviota does not disappear after attacking

### ISSUE THREAD

**Issue by Periwinks** [ronancpl/HeavenMS#500]
Gaviota (Outlaw skill) should drop one grenade, and then never return until the next time it is summoned (unlike other summons like phoenix/freezer/etc who will continue attacking after they've already attacked once). It also happens that this is mentioned in the tooltip

> Summons gaviota, who's trained to throw a grenade at monsters. The summoned gaviota will seek a monster, and when it finds one, it'll toss the grenade and disappear.

**Comment by ronancpl** [comment]
Issue solved, thanks for reporting!
