### ISSUE TITLE
Slowness

### ISSUE THREAD

**Issue by daronhudson** [ronancpl/HeavenMS#502]
Not sure if I saw this in the closed issues or if I just didn't see it, but the server takes a fairly long time to start up and moving between maps and logging into world are also fairly slow. 
Is there a reason why that might be happening? Running it on windows with very good specs.

**Comment by DannyG98** [comment]
I found the issue to not be with the server but the client. A restart of the client fixes the issue.

**Comment by daronhudson** [comment]
Doesn’t matter what I do, the server takes forever to finish starting up and portals/world login are always slow, even after a client reboot

**Comment by daronhudson** [comment]
It also works totally fine if I use a random blank v83 source

**Comment by ronancpl** [comment]
Server boot time has been reviewed on 7ee947b4041852b33832d856b464abfe0ceafb8e.

Events have been getting the most time elapsed when loading a channel (dozen seconds per world - 3 channels), furthermore, they shouldn't be needed for the player login phase... To alleviate this, events have been set to run its initialization course immediately after the server goes online. Hopefully, this should clear the slow initialization phase. Thanks for this feedback.

**Comment by daronhudson** [comment]
It would take multiple minutes per channel, it was extremely slow. I figured out the issue though. For whatever reason the server doesn’t cooperate with PFsense. Using it makes this happen, without running through it, it’s totally fine.
