### ISSUE TITLE
Max Quest Level

### ISSUE THREAD

**Issue by DannyG98** [ronancpl/HeavenMS#503]
There are some quests (i.e. Astaroth/Mushking) that have a max level requirement. Because of server rates and quest rates, it makes it impossible to complete and receive the reward at the end of the quest-line without surpassing the max level limit.

My attempt to fix it was by modifying the MaxLevelRequirement.java file to hardcode the maxlevel to be 200. However, this did not have any noticeable impact. I've looked through numerous files hoping to find anything related to the max level of quests but had no success. Can anyone point me in the right direction?

**Comment by ronancpl** [comment]
Unfortunately, limits on quest level are client-side logic, depicted within the client-side Wz files.

This leads to quest lightbulbs not showing to the player if their level already passed over the limits, the server doesn't even get to notice this behavior.

**Comment by xinyifly** [comment]
In my fork 5255d71 , I added 2 commands named "QuestRetrieve" and "QuestSkip" to retrieve missed quests and skip quests that already done in characters under same account. @DannyG98 @ronancpl If this is something pleased, I can send a pull request.
