### ISSUE TITLE
HeavenMS & JDK 12

### ISSUE THREAD

**Issue by ozanrijen** [ronancpl/HeavenMS#519]
Can we move on?

**Comment by ronancpl** [comment]
Hi, @ozanrijen

At the start, this repository worked with Java 7. Unfortunately, there are a few concerns to deal with before getting to update versions in the current stacks.

It generally configures eventual troubleshooting (mainly in scripts, but sometimes core changes are also to be expected) of issues that stem up from moving versions. A few could be found in scripts after the PR #489 that emerged Java 8, but hopefully those issues have been dealt with now (haven't got any hint of more issues from that move showing up).
