### ISSUE TITLE
Quest "Eliza's Eternal Sleep" (id:3114) can't complete.

### ISSUE THREAD

**Issue by kvmba** [ronancpl/HeavenMS#531]
![QQ截图20191013210304](https://user-images.githubusercontent.com/2517326/66716109-fafdf680-edfc-11e9-99ec-9af86186cd54.png) 

https://bbb.hidden-street.net/quest/el-nath-mt-aquaroad/goddess-pet
Can't get award, Server Console display nothing .

**Comment by ronancpl** [comment]
Hmm, from the frame it looks like you have access to the quest completion UI. From that, any transaction that may be blocking you from completing the quest should be server-side.

On how that quest used to be (a quest script), the quest used to have the progress checked by `qm.getQuestProgress(3114, 7777)`.

Said this, consider the following:

Try comparing the progress registered on DB: `SELECT a.characterid, quest, progress FROM queststatus a LEFT JOIN questprogress b ON a.queststatusid = b.queststatusid WHERE quest=3114`

With the progress expected by the script (which used to be -1, but now it goes as "42"):

![image](https://user-images.githubusercontent.com/9257761/66878680-6082ec00-ef91-11e9-9f8a-54a5122dc6b3.png)

![image](https://user-images.githubusercontent.com/9257761/66878739-b192e000-ef91-11e9-9be0-8ebca490a9c4.png)

A solution for that could be either manually change the value on DB to fulfill the player's quest progress, or make it so the 7 note scripts (from 2012027) updates towards the expected progress.

**Comment by ronancpl** [comment]
Issue patched, thanks for reporting!
