### ISSUE TITLE
Cash Item “Safety Charm"(id:5130000) not recovered HP&MP when  revived

### ISSUE THREAD

**Issue by kvmba** [ronancpl/HeavenMS#533]
![QQ截图20191016233602](https://user-images.githubusercontent.com/2517326/66935343-6ac6e800-f06e-11e9-86a4-d0ff223a39ef.png)

5130000 - Safety Charm - It does not let the user lose EXP points after death, as long as it's in possession. 30% of your HP and MP will be recovered when you are revived.

not implements。

**Comment by ronancpl** [comment]
Indeed. Not implemented yet, is it not?

**Comment by kvmba** [comment]
Not implemented yet

**Comment by ronancpl** [comment]
Yeah.

**Comment by ronancpl** [comment]
Feature now available.
