### ISSUE TITLE
Quest: "Operation Strategy 3: A Cute Baby Bird" (id:3250) Can't complete.

### ISSUE THREAD

**Issue by kvmba** [ronancpl/HeavenMS#534]
![QQ截图20191019010922](https://user-images.githubusercontent.com/2517326/67113913-3dfd0700-f20d-11e9-957e-8bcc3f098e51.png)

because Item: Springy Worm(4031992) Can't drop from monster ，（i killed over 300）
：）

**Comment by ronancpl** [comment]
Issue patched. Thanks for reporting!
