### ISSUE TITLE
Client Crash when talking with NPC PI:(NPCID:2040016) Ludibrium - Ludibrium Village(MAPID: 220000300 )

### ISSUE THREAD

**Issue by kvmba** [ronancpl/HeavenMS#536]
![QQ截图20191020022943](https://user-images.githubusercontent.com/2517326/67149830-a538bb00-f2e2-11e9-8e63-9211f48e8076.png)
![QQ截图20191020023036](https://user-images.githubusercontent.com/2517326/67149834-b7b2f480-f2e2-11e9-95a3-11d7a0352296.png)
![QQ截图20191020023213](https://user-images.githubusercontent.com/2517326/67149835-bb467b80-f2e2-11e9-8a58-2c3d28e50430.png)
![QQ截图20191020022956](https://user-images.githubusercontent.com/2517326/67149837-c4374d00-f2e2-11e9-9eee-e75234f92dfc.png)
--------------------------------------
1.talking to him
2.select "Create Arrows"
3.Option: 
“Arrow for Bow”                       ->Crash.
"Arrow for Crossbow"              ->Crash.
"Bronze Arrow for Bow"           ->Crash.
"Bronze Arrow for Crossbow"   ->Crash.
"Steel Arrow for Bow"              ->Crash.
"Steel Arrow for Crossbow"     ->Crash.

:)

**Comment by ronancpl** [comment]
Issue patched.
