### ISSUE TITLE
Some bugs about region Elllin Forest

### ISSUE THREAD

**Issue by yuxaij** [ronancpl/HeavenMS#537]
1. Please replace `java.lang.Math.min` with `Math.min` in the following four scripts: 
+ npc/2131006.js
+ npc/2131005.js
+ npc/2131001.js
+ npc/2131003.js

as they attempted to call the min func with an integer and a division expression, typically `java.lang.Math.min(300, cm.itemQuantity(exchangeItem) / 100)`. 
A simple script to search `java.lang.Math.min/max` in `HeavenMS/scripts` showed that only these four had the problem.

2. Line 116 in `npc/2133000.js` (EllinPQ's NPC script) 
```
cm.gainItem(1032101, 1); 
```
sends an non-existed equipment to the player and then cause a client crash when the player open his equip inventory.

**Comment by ronancpl** [comment]
Those issues are supposed to have been cleared out on d9f87f18a11415355af866e48f61f926532bc688. Please reopen should the issue persist.
