### ISSUE TITLE
SQL Foreign key Error (db_database.sql) in last commit.

### ISSUE THREAD

**Issue by kvmba** [ronancpl/HeavenMS#538]
![QQ截图20191029223034](https://user-images.githubusercontent.com/2517326/67776929-00fe0380-fa9c-11e9-8d63-732bafe8612d.png)

error code: 
ALTER TABLE `inventoryitems` ADD CONSTRAINT `fk_itempetid` FOREIGN KEY (`petid`) REFERENCES `pets` (`petid`) ON DELETE SET NULL ;  # thanks Optimist for noticing queries over petid taking too long, shavit for pointing out an improvement using foreign key

![QQ截图20191029223104](https://user-images.githubusercontent.com/2517326/67776990-15da9700-fa9c-11e9-93b4-7f68ebd7e121.png)

foreign key not exists.
: )

**Comment by ronancpl** [comment]
Issue patched.
