### ISSUE TITLE
Integration with HeavenClient

### ISSUE THREAD

**Issue by nansonzheng** [ronancpl/HeavenMS#539]
Hi @ronancpl, sorry if this isn't the right place to contact you but I couldn't find any contact details on your GitHub profile. I'm working on a team that is trying to bring a forked version of your server up, along with a custom client forked from @ryantpayton's [HeavenClient](https://github.com/ryantpayton/HeavenClient). We're having problems such as the client's game UI not visible and characters not dying properly.

Did you work with Ryan on integrating with HeavenClient? Were there any changes you made to the server to accommodate the client? Or this is entirely client-sided and the server has no control over it?

**Comment by ronancpl** [comment]
Hi @nansonzheng. As far as integration between server-client communication between the two software artifacts has gone, pardon possible bluntness, would plainly hang around the extent of the featured packet exchanges.

Serverside-wise... no, there didn't really have changes to make up for accommodations. The way the server sends packets is supposed to be on even grounds for any client that tries for a connection.

**Comment by nansonzheng** [comment]
Thanks. Do you know how if @ryantpayton is still maintaining HeavenClient, and if so, how can I contact him for advice about the client?

**Comment by xinyifly** [comment]
@nansonzheng There is a [discord channel](https://discord.gg/Q7wKxHX) introduced in [README.md](https://github.com/ronancpl/HeavenMS#support-heavenms) . ryantpayton is available there as well.

**Comment by nansonzheng** [comment]
Thanks, I'll try to contact him there.
