### ISSUE TITLE
Could Not Reserve Enough Space for Object Heap -- ERROR

### ISSUE THREAD

**Issue by panicco** [ronancpl/HeavenMS#541]
Error When launching fresh install, following guide

`Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Press any key to continue . . .`

**Comment by panicco** [comment]
setting launcher options to Xmx512m fixed issue. Launching now.

**Comment by ronancpl** [comment]
`Xmx` essentially allocates for the JVM a heap space in MB, to be used from the RAM.

Nice to have this issue cleared, this issue can be closed. If it's fully settled there as well, kindly consider closing it.

**Comment by ronancpl** [comment]
Appreciated.
