### ISSUE TITLE
NPC Locations

### ISSUE THREAD

**Issue by cihadpalta** [ronancpl/HeavenMS#544]
Hello everyone,

I noticed the NPC locations of the Regular Cabs in some cities (Kerning and Ellinia) are not located at the right spot, also for the Storage Keepers(?).
Is there a fix already to relocate the NPCs to the place where they belong?

Hope to hear from you asap.

Kind regards

**Comment by Lichtmager** [comment]
I'm not sure if this will help you but i had the same issue long ago with the location of many npcs in some areas.

What i did was dumping the wz of the maps where the npcs were not placed correctly using harepacker.

**Comment by cihadpalta** [comment]
Hi Lichtmager, 

Thanks for your message. Is there any possibility you can provide me with the right wz or xml files to fix this problem? It's quite annoying and I didn't manage to fix the problem using harepacker.

**Comment by ronancpl** [comment]
Hi cihadpalta,

You can reexport the XML's with HaRepacker, by placing generated XML's from Map onto the "wz/Map.wz" folder.

To achieve this, on v83 architecture:
- Use the HaRepacker with encryption "GMS (old)";
- RE-EXPORT (using the "Private Server..." exporting option).

I hope this helps, any questions still left let's see it through.
