### ISSUE TITLE
First attack on mobs not working?

### ISSUE THREAD

**Issue by Lichtmager** [ronancpl/HeavenMS#546]
As the title says, there are mobs configured with first attack that doesn't follow you for example: Rotten Skeletons, Dead Scarecrows, Twisted Jesters, Gobys, etc.. In Gobys after killing the house where they are supposed to be hidden, they split on the map, only 3 or 4 follow you but these simply split around and you have to chase after them. Also in chimney just a few ones follow the player.. is there a way to fix that? Maybe changing some numbers in the aggro section in config ? in that case wich ones and what value should i put on it?

**Comment by ronancpl** [comment]
![image](https://user-images.githubusercontent.com/9257761/70840557-dc62ae80-1df1-11ea-8b78-00d45901dcce.png)

![image](https://user-images.githubusercontent.com/9257761/70840602-2350a400-1df2-11ea-9c79-aabe913d27c4.png)

Well, autoaggro seems to be doing the job fine here...

To find out whether autoaggro packet is working as intended, try calling "!showpackets". Opcode id 189 (0xBD) should be appearing on the console.

**Comment by ronancpl** [comment]
![image](https://user-images.githubusercontent.com/9257761/70840705-d6210200-1df2-11ea-8e1f-41b6fb1c21ee.png)

Well, autoaggro seems to be working fine...

To check whether the autoaggro packet is being sent, try calling "!showpackets". The opcode 189 (0xBD) should be showing up on the console.

Overall, mobs should be able to chase the player as soon as a player gains controllability over the mob (with `aggroSwitchController`) and the flag `controllerHasAggro` is set true.

**Comment by Lichtmager** [comment]
Thanks for the reply, but seems that the monster who are far in the map, even having the firstattack with value 1 in the wz doesn't follow the character. The player must come closer to them to activate the first attack. What i like to do is make every mob wich have the firstattack value in 1 in the map follow the player even from far away instead chasing the mobs, because i personally think that the mobs must chase the players if they have the first attack turned on and not backwards.

**Comment by ronancpl** [comment]
Understood. It looks like a fine idea for an optional feature, actually not intended from the beginning...

As far as it could be mustered, it turns out `moveMonsterResponse(objectid, moveid, mobMp, aggro)` would only cast an aggro response if the player is sufficiently near the mob.

**Comment by ronancpl** [comment]
This issue should have been cleared on the recent commit 07fe495bfd584f524e0df7e61411cac188908bd7. Thanks for the feedback!
