### ISSUE TITLE
Editing Client using hexeditor

### ISSUE THREAD

**Issue by philos22** [ronancpl/HeavenMS#547]
Noob question for sure:
Do I just type my Hamachi IP in place of the default 127.0.0.1?

I get this error after trying to log in after starting the client: `Unable to log on as a master on IP`

tldr; I don't think I am editing my client correctly with hex

**Comment by philos22** [comment]
Could somebody guide me through transitioning from localhost -> Hamachi server?
eg. Editing config.yaml
Editing Client

**Comment by ronancpl** [comment]
Hi @philos22 ,

In order to avoid such an issue, either set the server parameter `USE_IP_VALIDATION = false` or use IP 127.0.0.1 to connect to the server (which should be running on the same machine you're using to play the game).
