### ISSUE TITLE
Not any portal showed in dimensional mirror.

### ISSUE THREAD

**Issue by nvidiati422** [ronancpl/HeavenMS#548]
The icon in dimensional mirror are all question mark no matter what level I am.
I can't go anywhere by it, is it normal ?

**Comment by ronancpl** [comment]
This shouldn't be an issue, as far as tests went beginner jobs on out-of-ordinary GM levels happened to work properly... Is there maybe an unexpected scenario you've been found on?

**Comment by nvidiati422** [comment]
I don't know if there's any difference between GMS and TMS, but you should be able to  teleport to any PQ map by  using dimensional mirror, but in my case, when I'm lv 200, the only icon that showed up in dimensional mirror is Dojo and nothing else.

**Comment by ronancpl** [comment]
As of v83 GMS MapleStory, those seem to be the areas available for Dimensional Mirror:

```
/*
	 * 0 = ariant colliseum
	 * 1 = Dojo
	 * 2 = Carnival 1
	 * 3 = Carnival 2
	 * 4 = Ghost Ship PQ?
	 * 5 = Pyramid PQ
	 * 6 = Kerning Subway
	 */
	public void sendDimensionalMirror(String text) {
		getClient().announce(MaplePacketCreator.getDimensionalMirror(text));
	}
```
