### ISSUE TITLE
Adding items to cash shop

### ISSUE THREAD

**Issue by philos22** [ronancpl/HeavenMS#551]
Is there a guide/instructions on adding more items to the cash shop? (eg. transparent glasses)

**Comment by Lichtmager** [comment]
Well, not exactly a guide but a way to make all (or almost all) items on CS is editing Etc.wz using harepacker.. 

Note: you will unlock every single item that can be buy at cs, and some other that dont. But some items are repeated with different prices, thats something you have to fix/edit by yourself..

Open harepacker, find the Etc.wz, open it and find Comodity.img, then dump the XML in a folder of your choice, i picked desktop, then open it with notepad+ and you will get a line or lines with the values of the items that appears and the others that don't.. What we have to do now is make all the items on sale, so we must replace the on sale values and the way to do it pressing Ctrl+F, then click on replace and change:

<int name="OnSale" value="0"/>    
for 
<int name="OnSale" value="1"/>

If everything goes fine you will replace around 6500 values on it. Next thing to do is saving the file and then ( i dont know if this is needed but as i did it i'll write it here too) we must replace the values in the Wz file as well, so go back to the harepacker and delete/remove the whole Comodity.img on it, then click on Tools>Import>XML and find the comodity file we just edited and import it ( make sure you click the Etc.wz line in the harepacker before import the comodity to import it sucessfully) it will now have the values, save the Wz file and replace the comodity in your source folder. 


Now open your source and there muct be all the items that were previously hidden in your CS.. 

Now if you want to add an especific item just find the code of the item in comodity.img and change the value Onsale to 1, dump the file in your source, save the wz and the item will appear on it.

Hope this helps.
