### ISSUE TITLE
unable to log-on as a master at ip Please check again

### ISSUE THREAD

**Issue by jie4869** [ronancpl/HeavenMS#553]
login

**Comment by ronancpl** [comment]
Answered by dangoron earlier on HeavenMS' Disc #chat 
![image](https://user-images.githubusercontent.com/9257761/71051639-ae4dd900-2127-11ea-8385-8f429153013f.png)

**Comment by ronancpl** [comment]
Answered by Dangoron on HeavenMS' Disc chat.
![image](https://user-images.githubusercontent.com/9257761/71051693-e228fe80-2127-11ea-8bce-7a13464febb7.png)

**Comment by ronancpl** [comment]
By the way, this should be an issue only when trying to run the game within the same machine domain from the server (this error is a fallback for another scenario where entering the game session renders a server ping of 127.0.0.1, in contrast with one's LAN/WAN IP on login session).
