### ISSUE TITLE
Dragon that leads to Leafre/ToT doesn't fly properly

### ISSUE THREAD

**Issue by Lichtmager** [ronancpl/HeavenMS#555]
Hello me again, i noticed an issue when traveling from Leafre to ToT and vice. When the character becomes a dragon, the dragon literally kinda teleport the character to the top of the screen when pressing the jump key instead doing slightly dashes as the dragon ussualy must do.. 

I know it's not a deadlock or something, just a thing i noticed.

**Comment by ronancpl** [comment]
Unfortunately, as far as tests have gone this seems to be a client-side problem... Apologies for not being able to help further.
