### ISSUE TITLE
Game crash after speaking to customizer NPC - KIN (ID: 9900000)

### ISSUE THREAD

**Issue by philos22** [ronancpl/HeavenMS#556]
If you are picking a face for example and then press the Escape while in the window chat with the NPC, the game will crash and the character's face will be set to 0 in the database. Manually setting a face value in the DB will resolve this issue...

**Comment by philos22** [comment]
NPC name is KIN
NPC ID is 9900000

**Comment by ronancpl** [comment]
Apologies, but couldn't reproduce this issue.

Is there any special treatment for this to happen?

**Comment by philos22** [comment]
I commented out the check codeblocks for gmlevel() in the code, not sure if that would introduce this bug...
I did that because I wanted non-gm's to be able to use the customizing feature as well.

**Comment by ronancpl** [comment]
I'm assuming perhaps you have commented this section altogether on the remove GM level chore.

```
if (mode != 1 || cm.getPlayer().gmLevel() < 1){
        cm.dispose();
        return;
    }
```

Perhaps this led to the issue at hand?

**Comment by philos22** [comment]
I will try to re-add this block with just the `mode != 1` condition
Will update this issue ticket once I do

**Comment by philos22** [comment]
Re-adding it has fixed the bug. Thanks
