### ISSUE TITLE
Damage Adjustment

### ISSUE THREAD

**Issue by philos22** [ronancpl/HeavenMS#557]
I've been flipping through the server code and cannot find the algorithm that determines how much damage is dealt by a skill.
Any suggestions on where I should look to adjust (buff/nerf) certain job skill/damages?

**Comment by ronancpl** [comment]
Mostly within client-side contents.

Damage-dealing wise, server-side one may find handlers that propagate the damage value informed by the player's client or does any form of checks over the received data.

**Comment by philos22** [comment]
I see, so mostly the wz files?

**Comment by ronancpl** [comment]
Right. You might be willing to check out some skill descriptor values, which holds data getting accounted for the damage dealt.

**Comment by ronancpl** [comment]
Closing this... As this repository is going for the archived state, for future references, consider following the [community hub](https://discord.gg/Q7wKxHX).
