### ISSUE TITLE
Carnival PQ to Source

### ISSUE THREAD

**Issue by dolev159** [ronancpl/HeavenMS#75]
Please if you can to add CarnivalPQ !
very important!

**Comment by ronancpl** [comment]
I can't, sorry. This event is quite the work to make it running smoothly. Expect someone to give a pull request if you want to have this here, I don't have any plans to add that here.

**Comment by vcoc** [comment]
Dude, put this CPQ on your own and send it to us. 👍

**Comment by ronancpl** [comment]
MCPQ has been finally added to the source, by the pull request #427. Thanks @dragoso for this contribution!
